"""Cibermoda, personalização, equipamento neural, implantes e voz."""

DATA = {
    ("Fashionware", "biomonitor"): ("Biomonitor", "+2 em Resistência a Tortura/Drogas."),
    ("Fashionware", "skinwatch"): ("Relógio Subcutâneo", "Relógio situado sob a epiderme."),
    ("Fashionware", "light_tattoo"): ("Tatuagem Leve", "Tatuagem decorativa."),
    ("Fashionware", "shift_tacts"): ("Holo-Contato", "Lentes de contato que mudam de cor."),
    ("Fashionware", "chem_skins"): ("Química de Pele", "Tintura que muda a cor ou o desenho da pele."),
    ("Fashionware", "synthskins"): ("Pele Sintética", "Tintura que muda a cor e o desenho da pele artificial."),
    ("Fashionware", "synthskin_turning_chip"): ("Chips de Ajuste de Pele Sintética", "Armazenam diferentes padrões e cores para Pele Sintética."),
    ("Fashionware", "techhair"): ("Tecocabelo", "Cabelo artificial emissor de luz ou cor."),
    ("Fashionware", "kill_display"): ("Contador de Baixas", "Visor de três dígitos."),
    ("Fashionware", "turn_onails"): ("Unhas Turn-On", "Unhas que mudam de cor."),
    ("Fashionware", "show_off_nails"): ("Unhas Show-Off", "Unhas que mudam de padrão."),
    ("Fashionware", "transparent_skin"): ("Pele Transparente", "ATR -1; -4 quando aplicada ao rosto."),
    ("Fashionware", "mood_skin"): ("Pele de Humor", "Muda de cor conforme o humor."),
    ("Fashionware", "skin_tattoo"): ("Tatuagem Logo-Line Dermatech", "Tatuagens de logotipo."),
    ("Fashionware", "nu_tek_tvskin"): ("TVSkin Nu-Tek", "Transforma sua pele em uma videotela."),
    ("Fashionware", "advanced_biomonitor"): ("Biomonitor Avançado", "Inclui transmissão de dados a até 2 km."),

    ("Cyberware Customisation", "etched_design"): ("Desenho Gravado", "-2.000 eb quando feito antes da instalação."),
    ("Cyberware Customisation", "unusual_colorization"): ("Colorização Incomum", "+2.000 eb se o cromo já estiver preso ao corpo. Preço por polegada."),
    ("Cyberware Customisation", "unusual_optic_colorization"): ("Colorização Óptica Incomum", "+2.000 eb se o ciberóptico já estiver preso ao corpo."),
    ("Cyberware Customisation", "limblite_processor"): ("Processador Limblite", "Processador."),
    ("Cyberware Customisation", "limblite_control_chip"): ("Chip de Controle Limblite", "Chip de controle adicional."),
    ("Cyberware Customisation", "custom_cyberware"): ("Ciberware Personalizado", "Ciberware modificado. Preço igual a 4x o valor-base."),

    ("NeuralWare", "neuralware_processor"): ("Equipamento Neural", "Processador básico, necessário para todos os sistemas neurais."),
    ("NeuralWare", "kerenzikov_boosterware"): ("Amplificador Kerenzikov", "+1 nos testes de Iniciativa por nível adquirido, até +2."),
    ("NeuralWare", "speedware_sandevistan"): ("Amplificador Sandevistan", "+3 nos testes de Iniciativa durante 5 turnos."),
    ("NeuralWare", "tactile_boost"): ("Amplificador Tátil", "Aumenta a sensibilidade: +2 em qualquer teste de Atenção tátil."),
    ("NeuralWare", "olifactory_boost"): ("Amplificador Olfativo", "+2 em Atenção e rastreamento pelo olfato; 50% de chance de localizar um odor."),
    ("NeuralWare", "pain_editor"): ("Editor de Dor", "Testes de Resistência são feitos com dificuldade dois níveis menor."),
    ("NeuralWare", "cybermodem_link"): ("Conexão com Cibermodem", "Permite conexão direta com um cibermodem."),
    ("NeuralWare", "cyberaudio_link"): ("Conexão com Ciberáudio", "Permite conexão direta com um módulo de ciberáudio."),
    ("NeuralWare", "vehicle_link"): ("Conexão com Veículo", "+2 na operação direta de veículos controlados por cibernética."),
    ("NeuralWare", "smartgun_link"): ("Conexão com Arma Inteligente", "+2 em ataques com Armas Inteligentes."),
    ("NeuralWare", "machine_tech_link"): ("Conexão com Máquina/Tec", "Permite controlar fábricas automáticas e máquinas de todos os portes."),
    ("NeuralWare", "dataterm_link"): ("Conexão com DataTerm", "Permite transferir informações de DataTerms para a memória interna."),
    ("NeuralWare", "interface_plugs"): ("Conectores Neurais", "Permitem conexão direta com Armas Inteligentes, veículos e outros equipamentos."),
    ("NeuralWare", "chipware_socket"): ("Soquete de Chipware", "Comporta até 10 chips e executa um número de chips igual à INT."),
    ("NeuralWare", "mag_duct_spots"): ("Pontos Mag-Duct", "Funcionam como Conectores Neurais, mas concedem apenas +1."),
    ("NeuralWare", "tactile_boost_linkage"): ("Acoplamento do Amplificador Tátil", "Liga o Amplificador Tátil a um Implante Sexual; causa dependência."),
    ("NeuralWare", "livewires"): ("LiveWires", "Cabos de interface preênseis."),
    ("NeuralWare", "pacemaker_coprocessor"): ("Coprocessador Marca-Passo", "Reinicia o coração quando atacado por ICE."),
    ("NeuralWare", "super_compact_braindance"): ("Braindance Supercompacto", "Gravador de Braindance instalado na parte de trás da cabeça."),
    ("NeuralWare", "model_100_plugs"): ("Conectores Modelo 100", "+2 contra Black ICE; -2 para qualquer outra função."),
    ("NeuralWare", "taste_boost"): ("Amplificador de Paladar", "+1 em Atenção baseada em paladar."),
    ("NeuralWare", "cyber_detection_computer"): ("Computador de Ciberdetecção", "Dispositivo de reconhecimento e detecção; exige Conexão com Máquina/Tec."),
    ("NeuralWare", "echolocation_system"): ("Sistema de Ecolocalização", "Permite enxergar na escuridão total, com -1 em Atenção."),
    ("NeuralWare", "lockdown"): ("Lockdown", "Usa o ciberáudio para localizar atiradores de precisão."),
    ("NeuralWare", "chiplok"): ("ChipLok", "Trava os chips no lugar."),
    ("NeuralWare", "boostmaster"): ("Boostmaster", "+1 REF quando os dois tipos de amplificador neural estão instalados."),
    ("NeuralWare", "subdermal_smartgun_link"): ("Conexão Subcutânea com Arma Inteligente", "Versão dos Pontos Mag-Duct exclusiva para armas; concede +1."),
    ("NeuralWare", "braindance_plugs"): ("Conectores de Braindance", "Permitem conexão direta com um gravador de Braindance."),
    ("NeuralWare", "neural_ulf_transceiver"): ("Transceptor Neural ULF", "Envia e recebe voz e dados. Alcance de 15 km ou ilimitado, conforme a conexão."),
    ("NeuralWare", "universal_link"): ("Conexão Universal", "Combina diversas funções de conexão neural."),
    ("NeuralWare", "positronic_enhancer"): ("Intensificador Positrônico", "+2 INT; 10% de chance de sobrecarga e convulsões."),
    ("NeuralWare", "braindance_apdaptor"): ("Adaptador de Braindance", "Permite executar Braindance por um Soquete de Chipware."),
    ("NeuralWare", "wirehead_unit"): ("Unidade Wirehead", "Estimula os centros de prazer do cérebro."),

    ("Implants", "nasal_filters"): ("Filtros Nasais", "Detêm gases tóxicos e poluição; 70% eficazes."),
    ("Implants", "gills_fresh_water"): ("Guelras", "Sistema de respiração aquática que funciona por 4 horas."),
    ("Implants", "gill_toxin_filters"): ("Filtros de Toxinas para Guelras", "Filtram toxinas por 1 hora e 30 minutos."),
    ("Implants", "saltwater_gills"): ("Guelras de Água Salgada", "Sistema de respiração em água salgada que funciona por 4 horas."),
    ("Implants", "independent_air_supply"): ("Suprimento Independente de Ar", "Fornece ar por 10 a 25 minutos."),
    ("Implants", "independent_air_supply_plus"): ("Suprimento Independente de Ar +", "Fornece ar por 50 minutos."),
    ("Implants", "mr_studd"): ("Implante Sexual Mr. Studd", "Todas as noites, a noite toda. +1 em testes de Sedução."),
    ("Implants", "midnight_lady"): ("Implante Midnight Lady", "Implante sexual. +1 em testes de Sedução."),
    ("Implants", "contraceptive_implant"): ("Implante Contraceptivo", "Válido por 5 anos; 98% eficaz."),
    ("Implants", "subdermal_pocket"): ("Bolso Subcutâneo", "Espaço de 5 x 10 cm com zíper de RealSkinn; difícil de notar."),
    ("Implants", "adrenal_booster"): ("Intensificador de Adrenalina", "+1 REF por 1D6+2 turnos, até três vezes por dia."),
    ("Implants", "subdermal_armor"): ("Armadura Subcutânea", "Protege o tronco com PB 18; difícil de notar."),
    ("Implants", "subdermal_torso_armour"): ("Armadura Subcutânea de Tronco", "PB 6 a 22; de quase impossível a fácil de notar; reduz REF e ATR."),
    ("Implants", "subdermal_skull_armour"): ("Armadura Subcutânea de Crânio", "PB 4 a 14; de quase impossível a fácil de notar; 60% de cobertura."),
    ("Implants", "motion_detector"): ("Detector de Movimento", "Detecta movimentos em uma área de 20 m²; 70% eficaz."),
    ("Implants", "digital_recorder"): ("Gravador Digital", "Armazena 2 horas de qualquer fonte digital."),
    ("Implants", "audio_video_tape_recorder"): ("Gravador de Vídeo/Áudio", "Armazena 2 horas de conexões de vídeo e áudio."),
    ("Implants", "radar_sensor"): ("Radar", "Alcance de 100 m; exige ciberóptico; 70% eficaz."),
    ("Implants", "sonar_implant"): ("Implante de Sonar", "Alcance de 50 m; funciona apenas na água; 70% eficaz."),
    ("Implants", "military_sonar"): ("Sonar Militar", "Alcance de 50 m; apenas para água; 95% eficaz. Disponibilidade P."),
    ("Implants", "radiation_detector"): ("Detector de Radiação", "Alcance de 10 m; 80% eficaz."),
    ("Implants", "chemical_analyser"): ("Analisador Químico", "Alcance de 5 m; 70% eficaz."),
    ("Implants", "t_maxx_cyberliver"): ("Ciberfígado T-Maxx", "+4 contra drogas e venenos ingeridos."),
    ("Implants", "t_maxx2_cyberliver"): ("Ciberfígado T-Maxx 2", "Como o modelo anterior, mas com sistema de redirecionamento de fluidos."),
    ("Implants", "decentralized_heart"): ("Coração Descentralizado", "+2 em Testes de Morte causados por ferimentos no tronco."),
    ("Implants", "e_monitor"): ("Monitor Ambiental", "Detecta mudanças de pressão e do ar."),
    ("Implants", "gyro_stabilizer"): ("Giroestabilizador", "+1 em manobras de equilíbrio."),
    ("Implants", "optishield"): ("OptiShield", "Proteção Anti-Ofuscante, PB 8 e dois espaços para opções ópticas."),
    ("Implants", "optishield_options"): ("Opções OptiShield", "T2, T2+, TE, LB, IV e data/hora."),
    ("Implants", "pacesetter_heart"): ("Coração Pacesetter", "+1 MA e TIPO CORPORAL enquanto estiver ativo."),
    ("Implants", "pacesetter_2000_heart"): ("Coração Pacesetter 2000", "+2 MA e TIPO CORPORAL enquanto estiver ativo."),
    ("Implants", "variable_chambered_heart"): ("Coração de Câmaras Variáveis", "Opção para cibercoração: dobra o tempo sem respirar e concede +1 em Resistência."),
    ("Implants", "rebreather_enhanced_lungs"): ("Respirador/Pulmões Reforçados", "Permite prender a respiração por 15 minutos."),
    ("Implants", "wet_drive"): ("Wet Drive", "Armazena 1 UM de dados."),
    ("Implants", "extraemory"): ("Memória Extra", "+1 UM."),
    ("Implants", "wetdrive_access_link"): ("Conexão de Acesso ao Wet Drive", "Conexão interna para o Wet Drive."),
    ("Implants", "wearmank2"): ("Wearman Mk. 2", "Pode ser usado sem ciberáudio."),
    ("Implants", "subdermal_viewscreen"): ("Videotela Subcutânea", "Videotela subcutânea de 30 x 60 cm."),
    ("Implants", "zetatech_bodycomp"): ("BodyComp Zetatech", "Equivale a um E-Book."),
    ("Implants", "eye_color_gland_control"): ("Controle Glandular da Cor dos Olhos", "Muda a cor dos olhos em 1D6 minutos."),
    ("Implants", "autoinjector"): ("Autoinjetor", "Comporta cinco doses; +200 eb para conectá-lo ao Biomonitor."),
    ("Implants", "cell_phone_implant"): ("Implante de Telefone Celular", "Telefone celular implantado."),
    ("Implants", "cam_o_skin"): ("Cam-O-Skin", "-1 em Atenção a cada 20 m; oito padrões; mudança leva 1 hora."),
    ("Implants", "endo_frame_basic"): ("Endoarmação Básica", "TIPO CORPORAL +3, +1 dano corpo a corpo, 10 pontos por membro e EV +1."),
    ("Implants", "endo_frame_orbital"): ("Endoarmação Orbital", "TIPO CORPORAL +3, +2 em todo dano e 12 pontos por membro."),
    ("Implants", "bodyweight_vein_clips"): ("Clipes Venosos Bodyweight", "+2 em todos os Testes de Morte."),
    ("Implants", "militech_cyberdoc"): ("Cyberdoc Militech", "Neutraliza drogas e substâncias semelhantes."),
    ("Implants", "boozemaster"): ("BoozeMaster", "+1 para resistir ao álcool."),
    ("Implants", "gpsodule"): ("Módulo GPS", "Determina a posição com precisão de 17 cm; exige T2 ou T2+."),
    ("Implants", "gpsodule_screen"): ("Módulo GPS com Tela", "Como o modelo anterior, mas inclui uma Videotela Subcutânea."),
    ("Implants", "otec_ear_valve"): ("Válvula Auricular OTEC", "Sistema de equalização de pressão."),
    ("Implants", "enhanced_lungs_series2"): ("Pulmões Reforçados Série 2", "Permitem prender a respiração por 5 a 30 minutos e suportam 200 m de profundidade."),
    ("Implants", "enhanced_lungs_series3x2"): ("Pulmões Reforçados Série 3", "Substituem os pulmões inteiros e suportam até 1.000 m de profundidade."),
    ("Implants", "feel_good_endorphin_trigger"): ("Gatilho de Endorfina Feel Good", "Ao sofrer dano, role 1D10: 8-10 concede +3 em Atordoamento/Morte; 1 causa intoxicação."),
    ("Implants", "poison_sac"): ("Bolsa de Veneno", "Reservatório de veneno."),
    ("Implants", "uv_blockers"): ("Bloqueadores UV", "Resistência a UV e infravermelho."),
    ("Implants", "feature_alteration_implant"): ("Implante de Alteração Facial", "Permite mudança facial rápida."),
    ("Implants", "strobe_m"): ("Estrobo", "Cega por 1D6 horas; opção para implante Flashlite."),
    ("Implants", "life_scan_bodyonitor"): ("Monitor Corporal Life Scan", "+1 COOL, +4 em Primeiros Socorros e +1 em Testes de Morte."),
    ("Implants", "self_destruct"): ("Autodestruição", "Ativa após a morte quando o corpo é movido; raio de 5 m."),

    ("Voice Box", "dakai_cyphire_new_throat"): ("Nova Garganta Dakai/Cyphire", "Comporta três implantes ou opções por 1/4 do preço em eb, PH 0 e 15 PDE."),
    ("Voice Box", "cybervocal_boxalter"): ("Cybervocal BoxAlter", "Uma opção e uma voz."),
    ("Voice Box", "voice_synthesizer"): ("Sintetizador de Voz", "Pode reproduzir, com 60% de precisão, até 10 sons gravados."),
    ("Voice Box", "audiovox"): ("AudioVox", "Sintetizador vocal para efeitos especiais; +2 em Atuação."),
    ("Voice Box", "forked_tongue"): ("Língua Bifurcada", "Opção para AudioVox/Nova Garganta; +1 em Persuasão e Sedução."),
    ("Voice Box", "voice_pattern"): ("Padrão Vocal", "Opção para AudioVox/Nova Garganta que permite emular padrões de voz."),
    ("Voice Box", "scramble"): ("Embaralhador", "Opção para AudioVox/Nova Garganta que embaralha a voz."),
    ("Voice Box", "volume"): ("Volume", "Vai de sussurro a megafone; ensurdece por 1D6 turnos a até 5 m."),
    ("Voice Box", "armour"): ("Blindagem", "Apenas para Nova Garganta; PB 20."),
    ("Voice Box", "subsonic"): ("Subsônico", "Só pode ser ouvido com audição subsônica."),
}
