"""Instalações internas, ciberarmas, armações, blindagem e Full 'Borgs."""

DATA = {
    ("Cyberlimbs Builtins", "cybermodem"): ("Cibermodem", "Ciberdeck embutido."),
    ("Cyberlimbs Builtins", "cellular_cybermodem"): ("Cibermodem Celular", "Ciberdeck celular embutido."),
    ("Cyberlimbs Builtins", "digital_recorder"): ("Gravador Digital", "Gravador digital de chip; permite baixar ou apagar o chip."),
    ("Cyberlimbs Builtins", "storage_space"): ("Espaço para Armazenamento", "Espaço interno de 5 x 15 cm que pode ser trancado."),
    ("Cyberlimbs Builtins", "minicam"): ("Minicâmera", "Câmera digital retrátil com 20 fotos."),
    ("Cyberlimbs Builtins", "minivid"): ("Minivídeo", "Câmera de vídeo retrátil com 30 minutos de gravação."),
    ("Cyberlimbs Builtins", "hidden_holster"): ("Coldre Oculto", "O tamanho da arma depende do Tipo Corporal."),
    ("Cyberlimbs Builtins", "lcd_screen_readout"): ("Monitor de Cristal Líquido", "Pode ser conectado a qualquer dispositivo de saída."),
    ("Cyberlimbs Builtins", "techscanner"): ("Tecscanner", "60% eficaz; reduz em 3 a dificuldade de reparos."),
    ("Cyberlimbs Builtins", "cutting_torch"): ("Maçarico de Corte", "Corta materiais com até PB 20."),
    ("Cyberlimbs Builtins", "icer"): ("Icer", "Alcance de 2 m."),
    ("Cyberlimbs Builtins", "limb_link"): ("Conexão de Membro", "Transforma uma arma retrátil em Arma Inteligente e concede +1."),
    ("Cyberlimbs Builtins", "magnetic_hands_feet"): ("Mãos/Pés Magnéticos", "Facilitam a movimentação em gravidade zero."),
    ("Cyberlimbs Builtins", "watch_man"): ("Watch-Man", "Televisor em miniatura."),
    ("Cyberlimbs Builtins", "winch"): ("Guincho", "Cabo de 15 m capaz de puxar até uma tonelada."),
    ("Cyberlimbs Builtins", "quickdraw_holster"): ("Coldre de Saque Rápido", "Ocultabilidade de classe P; +2 na Iniciativa para saque rápido."),
    ("Cyberlimbs Builtins", "radio_phone_station"): ("Estação de Rádio-Telefone", "Funciona por 160 horas por carga; ocupa dois espaços."),
    ("Cyberlimbs Builtins", "ecm"): ("ECM", "Contramedidas eletrônicas; ocupa dois espaços."),
    ("Cyberlimbs Builtins", "laser_mike"): ("Microfone Laser", "Alcance de 60 m; Percepção Humana -5."),
    ("Cyberlimbs Builtins", "cyberpillow"): ("CyberPillow", "Um travesseiro embutido no braço."),
    ("Cyberlimbs Builtins", "smartplate_link"): ("Conexão Smartplate", "Faz a Arma Inteligente custar 3x o preço normal."),
    ("Cyberlimbs Builtins", "microwaldo_bracer"): ("Braçadeira Microwaldo", "+1 em testes de TEC."),
    ("Cyberlimbs Builtins", "dtek_targeting_network"): ("Rede de Mira D-Tek", "Anula os modificadores por disparar em movimento."),
    ("Cyberlimbs Builtins", "ufl_antena"): ("Antena ULF", "Antena de carretel de 100 m para o transceptor."),
    ("Cyberlimbs Builtins", "cyberlimb_light"): ("Luz de Cibermembro", "Luz embutida na palma, alcance de 3 m e nenhum espaço ocupado."),

    ("Cyberweapons Builtins", "grenade_launcher"): ("Lançador de Morteiro", "Comporta duas granadas de qualquer tipo."),
    ("Cyberweapons Builtins", "micro_missile_launcher"): ("Lançador de Micromísseis", "Contém quatro minimísseis que causam 4D6 de dano cada."),
    ("Cyberweapons Builtins", "popup_gun"): ("Arma Retrátil", "O tamanho depende do Tipo Corporal. Preços variados entre 2 e 800 eb."),
    ("Cyberweapons Builtins", "flame_thrower"): ("Lança-Chamas", "Alcance de 1 m, quatro disparos; causa 2D6 e depois 1D6/2 de dano."),
    ("Cyberweapons Builtins", "weapon_mount_link"): ("Adaptador para Arma e Conexão", "Placa de adaptação e conexão neural para uma arma."),
    ("Cyberweapons Builtins", "two_shot_capacitor_laser"): ("Laser de Capacitor de Tiro Duplo", "Montado no ombro; dano 3D6 e alcance de 10 m."),
    ("Cyberweapons Builtins", "derringer"): ("Derringer", "Pistola 5 mm; dano 1D6 e alcance de 50 m."),
    ("Cyberweapons Builtins", "flashbulb"): ("Lâmpada de Clarão", "Afeta uma área de 4 x 6 m."),
    ("Cyberweapons Builtins", "gas_jet"): ("Jato de Gás", "Seis disparos, alcance de 2 m e dano 1D6+3."),
    ("Cyberweapons Builtins", "tazer_grip"): ("Empunhadura Taser", "Efeitos iguais aos de um taser; Atordoamento -2."),
    ("Cyberweapons Builtins", "whip"): ("Chicote", "Dano 1D6/2 ou estrangulamento."),
    ("Cyberweapons Builtins", "popup_sliver_gun"): ("Arma de Estilhaços Retrátil", "Dano 2D6x1D6/2* e alcance de 40 m."),
    ("Cyberweapons Builtins", "tri_dart_launcher"): ("Lançador de Três Dardos", "Três dardos, dano 1D6/2 e 1/3 do PB."),
    ("Cyberweapons Builtins", "retractable_monoblade"): ("Monolâmina Retrátil", "Dano 2D6+3#."),
    ("Cyberweapons Builtins", "survival_blade"): ("Lâmina de Sobrevivência", "Dano 1D6+3*."),
    ("Cyberweapons Builtins", "chainripp"): ("ChainRipp", "Dano 3D6 PA."),
    ("Cyberweapons Builtins", "blitzkrieg_arc_thrower"): ("Lançador de Arco Blitzkrieg", "Dano 3D6, metade real e metade de atordoamento; alcance de 10 m."),
    ("Cyberweapons Builtins", "bigripp"): ("BigRipp", "Lâmina de carbovidro; dano 2D6, metade do PB e quebra com 1-3."),
    ("Cyberweapons Builtins", "high_five_palm_bomb"): ("High Five/Bomba de Palma", "Dificuldade 20-30 para detectar; munição .477 ou calibre 12; um disparo."),
    ("Cyberweapons Builtins", "pop_up_hand_crossbow"): ("Besta de Mão Retrátil", "Dano 1D6+2, alcance de 25 m e três espaços."),
    ("Cyberweapons Builtins", "micro_torpedo_launcher"): ("Lançador de Microtorpedos", "Versão subaquática do Lançador de Micromísseis."),

    ("Linear Frame", "sigma"): ("Armação Sigma", "FORÇA 12 e modificador de dano +4."),
    ("Linear Frame", "beta"): ("Armação Beta", "FORÇA 14 e modificador de dano +6."),
    ("Linear Frame", "omega"): ("Armação Ômega", "FORÇA 16 e modificador de dano +8."),
    ("Linear Frame", "gp_exoskeleton_a"): ("Exoesqueleto GP - A", "FORÇA 18, 15 PDE, PB 6, MA 4 e REF 5."),
    ("Linear Frame", "gp_exoskeleton_b"): ("Exoesqueleto GP - B", "FORÇA 21, 20 PDE, PB 8, MA 4 e REF 5."),
    ("Linear Frame", "underwater_gamma"): ("Armação Subaquática Gama", "FORÇA 12/10."),
    ("Linear Frame", "underwater_delta"): ("Armação Subaquática Delta", "FORÇA 14/12."),
    ("Linear Frame", "underwater_pi"): ("Armação Subaquática Pi", "FORÇA 16/14."),

    ("Bodyplating", "cowl"): ("Capuz", "Cobre a cabeça com PB 25."),
    ("Bodyplating", "faceplate"): ("Placafacial", "Máscara facial protetora com PB 25."),
    ("Bodyplating", "torso_plate"): ("Placa de Tronco", "Proteção para o tronco com PB 25 e REF -3."),
    ("Bodyplating", "front_optic_mount"): ("Adaptador Frontal Óptico", "Permite montar até cinco opções ópticas no rosto; ATR -1."),
    ("Bodyplating", "sense_ext_rabbit_ears"): ("Extensor de Sentidos - Orelhas de Coelho", "Extensores montados na cabeça para áudio, ópticos e outros sensores."),
    ("Bodyplating", "total_body_plating"): ("Blindagem Corporal Total", "PB 20, REF -3, ATR pela metade e -1 em Furtividade."),
    ("Bodyplating", "cyberfacial_remounts"): ("Remontagens Ciberfaciais", "PB 6 a 18, ATR -1 ou -2 e 15% a 50% de proteção."),
    ("Bodyplating", "spyke_furniture"): ("Ferragens Spyke!", "PB 10, +10 PDE e dano PA de 1D3+1 a 1D6+1."),

    ("Full'Borgs", "alpha_class"): ("Classe Alpha", "REF 10, MA 10, TIPO CORPORAL 12, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "aquarius_sub_marine"): ("Aquarius - Submarino", "REF 10, MA 10, TIPO CORPORAL 15, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "copernicus_space_use"): ("Copernicus - Uso Espacial", "REF 11, MA 10, TIPO CORPORAL 12, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "eclipse_covert_ops"): ("Eclipse - Operações Secretas", "REF 13, MA 13, TIPO CORPORAL 12, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "enforcer_security"): ("Enforcer - Segurança", "REF 12, MA 15, TIPO CORPORAL 12, PB 30 e PDE 25/35/45."),
    ("Full'Borgs", "brimstone_fire_fighter"): ("Brimstone - Bombeiro", "REF 11, MA 10, TIPO CORPORAL 14, PB 30 e PDE 20/30/40."),
    ("Full'Borgs", "gemini_humanoid"): ("Gemini - Humanoide", "REF 10, MA 10, TIPO CORPORAL 12, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "wingman_pilot"): ("Wingman - Piloto", "REF 15, MA 10, TIPO CORPORAL 12, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "samson_industrial"): ("Samson - Industrial", "REF 10, MA 10, TIPO CORPORAL 18, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "dragoon_military"): ("Dragoon - Militar", "REF 15, MA 25, TIPO CORPORAL 20, PB 40 e PDE 40/50/60."),
    ("Full'Borgs", "sheol_hazardous_ops"): ("Sheol - Operações de Risco", "REF 10, MA 10, TIPO CORPORAL 18, PB 30 e PDE 20/30/40."),
    ("Full'Borgs", "md_tech_kildare_medical"): ("MD Tech Kildare - Médico", "REF 10, MA 10, TIPO CORPORAL 12, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "adrek_burroughs_mars_ops"): ("Adrek Burroughs - Operações em Marte", "REF 10, MA 10, TIPO CORPORAL 12, PB 35 e PDE 20/30/40."),
    ("Full'Borgs", "militech_spyder_recon"): ("Militech Spyder - Reconhecimento", "REF 12, MA 20, TIPO CORPORAL 12, PB 30 e PDE 20/30/40."),
    ("Full'Borgs", "wiseman_cyberspace_com"): ("Wiseman - Comunicação no Ciberespaço", "REF 14, MA 10, TIPO CORPORAL 12, PB 25 e PDE 20/30/40."),
    ("Full'Borgs", "arasaka_daioni_pa_convert"): ("Arasaka Daioni - Conversão PA", "REF 17, MA 20, TIPO CORPORAL 52, PB 80 e +6 em Iniciativa."),

    ("Full Borg Options", "stylization"): ("Estilização", "Personalização que concede bônus a algumas perícias."),
    ("Full Borg Options", "increased_sp"): ("PB Aumentado", "Máximo de PB 40; aumenta o peso em 4,5 a 22,7 kg."),
    ("Full Borg Options", "increased_sdp"): ("PDE Aumentado", "Máximo de +20 PDE; +25 kg de peso a cada +5 PDE."),
    ("Full Borg Options", "increased_ref"): ("REF Aumentado", "Máximo de 15."),
    ("Full Borg Options", "increased_ma"): ("MA Aumentado", "Máximo de 25."),
    ("Full Borg Options", "increased_body"): ("TIPO CORPORAL Aumentado", "Máximo de 20."),
    ("Full Borg Options", "shielding"): ("Blindagem Eletrônica", "Proteção eletrônica."),
    ("Full Borg Options", "quick_change_mounts"): ("Adaptadores de Mudança Rápida", "Permitem montar rifles em dois pontos e armas pesadas em três."),
    ("Full Borg Options", "interchangeable_bipod"): ("Bípede Intercambiável", "Permite transferir órgãos entre diferentes corpos Full 'Borg."),
    ("Full Borg Options", "longevity_module"): ("Módulo de Longevidade", "Em teoria, triplica a vida útil do 'borg."),
    ("Full Borg Options", "eelskin"): ("Pele de Enguia", "Dano de 1D6 a 2D6+3."),
    ("Full Borg Options", "cyber_steroids"): ("Ciberesteroides", "TIPO CORPORAL x3; +3 kg por +1 TIPO CORPORAL; usa a unidade de energia abaixo."),
    ("Full Borg Options", "back_mounted_power_unit"): ("Unidade de Energia Dorsal", "+5% de peso, 10 horas de uso e 20 eb por recarga."),
    ("Full Borg Options", "variable_spectrum_light"): ("Luz de Espectro Variável", "Não ocupa espaços."),
    ("Full Borg Options", "enhanced_thermograph"): ("Termógrafo Aprimorado", "Termógrafo avançado; ocupa um espaço."),
    ("Full Borg Options", "blood_iv_supply"): ("Suprimento de Sangue/IV", "Quatro recipientes de 250 ml; ocupa um espaço."),
    ("Full Borg Options", "reactive_body_plating"): ("Blindagem Corporal Reativa", "Detecta miras laser e inteligentes; REF acima de 10 permite esquiva."),
    ("Full Borg Options", "dummy_facemasks"): ("Máscaras Faciais Falsas", "Placas faciais removíveis."),
}
