"""Ciberarmas corporais, ciberópticos e ciberáudio."""

DATA = {
    ("Bodyweapons", "scratchers"): ("Arranhadores", "Mãos; dano 1D6/3*; quase impossíveis de notar."),
    ("Bodyweapons", "implanted_fangs_vampires"): ("Presas Implantadas - Vampiros", "Boca; dano de 1D6/3* a 1D6/2*."),
    ("Bodyweapons", "poison_vampires"): ("Vampiros Venenosos", "Boca; dano 1D6/3* mais veneno ou droga."),
    ("Bodyweapons", "retractable_vampires"): ("Vampiros Retráteis", "Boca; dano de mordida de 1D6/3* a 1D6*."),
    ("Bodyweapons", "spitting_cobra"): ("Cobra Cuspidora", "Vampiros que cospem agentes químicos a até 1,8 m."),
    ("Bodyweapons", "rippers"): ("Estripadores", "Mãos; dano 1D6+3*; difíceis de notar."),
    ("Bodyweapons", "wolvers"): ("Garras", "Mãos; dano 3D6*."),
    ("Bodyweapons", "big_knucks"): ("Soqueira de Aço", "Mãos; dano 1D6+2."),
    ("Bodyweapons", "slice_n_dice"): ("Picador", "Mãos; dano 2D6#."),
    ("Bodyweapons", "cybersnake"): ("Cibercobra", "Ciberarma autocontrolada; dano 1D6*."),
    ("Bodyweapons", "gang_jazzler"): ("Gang Jazzler", "Três descargas; imobiliza por 1D10+1 minutos."),
    ("Bodyweapons", "bonespike"): ("Espinho Ósseo", "Espinho ósseo retrátil; dano 1D6+4*."),
    ("Bodyweapons", "newteeth"): ("NewTeeth", "Dentes de cerâmica: MEL -1, NA, C, 1-2 pts., NA, 1, VR."),
    ("Bodyweapons", "powerjaw"): ("PowerJaw", "Musculatura mandibular de miômero; +2 no dano de mordida."),
    ("Bodyweapons", "stinger"): ("Ferrão", "Agulha hipodérmica montada no dedo; três doses."),
    ("Bodyweapons", "bigripp"): ("BigRipp", "Dano 2D6*; quebra com 1, ou com 1-3 ao aparar."),
    ("Bodyweapons", "noveltech_spitfire_flamer"): ("Lança-Chamas Spitfire NovelTech", "EX +0 - P, preço variável, 4, 1, ST, alcance de 4 m."),
    ("Bodyweapons", "mandibles"): ("Mandíbulas", "Mordida de 2D6; parecem normais, exceto durante a alimentação."),
    ("Bodyweapons", "cyberjaw"): ("Cibermandíbula", "Mandíbula metálica PB 6; dano de mordida de 1D6* a 3D6*."),
    ("Bodyweapons", "cyberjaw_with_realskinn"): ("Cibermandíbula com RealSkinn", "Cibermandíbula revestida de RealSkinn."),

    ("Cyberoptics", "cyberoptic"): ("Ciberópticos", "Módulo ocular básico com quatro espaços de opção por olho."),
    ("Cyberoptics", "remote_eye"): ("Olho Remoto", "Mantém um espaço livre e transmite a até 100 m."),
    ("Cyberoptics", "optical_interface"): ("Interface Óptica", "Conector de interface atrás do ciberóptico."),
    ("Cyberoptics", "bug_eye"): ("Olho de Inseto", "Comporta seis opções."),
    ("Cyberoptics", "third_eye"): ("Terceiro Olho", "-1 ATR por olho; máximo de dois olhos extras."),
    ("Cyberoptics", "revelation_cyberoptic"): ("Ciberóptico Revelation", "Modelo antigo; +1 em Notar; ATR -1 ou -2."),
    ("Cyberoptics", "soviet_cyberoptic"): ("Ciberóptico Soviético", "Um espaço de opção por olho; 50% de chance de ATR -1."),
    ("Cyberoptics", "kiroshi_monovision"): ("MonoVision Kiroshi", "+1 em Notar e na Iniciativa contra emboscadas."),
    ("Cyberoptics", "quick_change_optic"): ("Ciberóptico de Mudança Rápida", "Removível, mas comporta apenas três opções."),

    ("Cyberoptics Options", "color_shift"): ("Mudança de Cor", "Permite mudanças de cor e efeitos especiais de moda."),
    ("Cyberoptics Options", "image_enhancement"): ("Imagem Melhorada", "+2 em Atenção/Notar durante uma varredura visual."),
    ("Cyberoptics Options", "targeting_scope"): ("Mira Telescópica", "+1 em todos os ataques com Armas Inteligentes."),
    ("Cyberoptics Options", "times_square_marquee"): ("Times Square Marquee", "Tela de LED no campo de visão para receber mensagens."),
    ("Cyberoptics Options", "teleoptics"): ("Telópticos", "Ampliação telescópica de até 20x."),
    ("Cyberoptics Options", "micro_optics"): ("Micro-Ópticos", "Microscópio."),
    ("Cyberoptics Options", "anti_dazzle"): ("Proteção Anti-Ofuscante", "Imunidade a clarões e cegueira por laser."),
    ("Cyberoptics Options", "low_lite"): ("LowLight (Luz Baixa)", "Permite enxergar em luz tênue, quase na escuridão total."),
    ("Cyberoptics Options", "thermograph_sensor"): ("Sensor Termográfico", "Exibe padrões de calor e leituras de temperatura."),
    ("Cyberoptics Options", "infrared"): ("Infravermelho", "Permite enxergar na escuridão total pelas emissões de calor."),
    ("Cyberoptics Options", "ultraviolet"): ("Ultravioleta", "Permite enxergar no escuro usando um flash UV."),
    ("Cyberoptics Options", "microvideo_optic"): ("Microvídeo", "Grava até 20 minutos de vídeo; ocupa dois espaços."),
    ("Cyberoptics Options", "digital_camera"): ("Câmera Digital", "Capta até 20 imagens; ocupa dois espaços."),
    ("Cyberoptics Options", "dartgun"): ("Pistola de Dardo", "Comporta um dardo envenenado; alcance de 1 m; ocupa três espaços."),
    ("Cyberoptics Options", "dodgeball"): ("Dodgeball", "+1 em Luta após 30 segundos."),
    ("Cyberoptics Options", "tear_gas_sprayer"): ("Esguicho de Gás Lacrimogêneo", "Alcance de 1 m; ocupa dois espaços."),
    ("Cyberoptics Options", "times_square_plus"): ("Times Square Plus", "Permite recuperar informações visualmente; ocupa três espaços."),
    ("Cyberoptics Options", "video_cam_transmitter"): ("Câmera de Vídeo/Transmissor", "Transmissão ao vivo com alcance de 1 m; ocupa quatro espaços."),
    ("Cyberoptics Options", "video_imager"): ("Receptor de Vídeo", "Recebe imagens de vídeo; ocupa dois espaços."),
    ("Cyberoptics Options", "time_day_display"): ("Visor de Data/Hora", "Exibe data e hora sem ocupar espaços."),
    ("Cyberoptics Options", "cyberoptic_compass"): ("Bússola Ciberóptica", "Ocupa um espaço, ou dois na versão Logocompass."),
    ("Cyberoptics Options", "interferometry_system"): ("Sistema de Interferometria", "Mantém a visão ampliada em 10x o tempo todo."),
    ("Cyberoptics Options", "laser_comm_optic"): ("Óptico de Comunicação a Laser", "Alcance de 50 m e capacidade de cegar; chips de código custam 175 eb."),
    ("Cyberoptics Options", "verbal_eyes_basic"): ("Olhos Verbais - Básico", "Exibem imagens; menos um espaço disponível."),
    ("Cyberoptics Options", "verbal_eyes_vid_image"): ("Olhos Verbais - Imagem de Vídeo", "Inclui Receptor de Vídeo."),
    ("Cyberoptics Options", "verbal_eyes_cust_image"): ("Olhos Verbais - Imagem Personalizada", "Preço igual ao dobro do valor-base mais 1.200 eb."),
    ("Cyberoptics Options", "double_slit_pupils"): ("Pupilas de Fenda Dupla", "Permitem visão nítida através da divisa entre ar e água; ocupa um espaço."),
    ("Cyberoptics Options", "hydrosubsidium_aquagoggs"): ("Aquagoggs Hydrosubsidium", "Membranas nictitantes sintéticas eficazes até 200 m de profundidade."),
    ("Cyberoptics Options", "live_feed_optic"): ("Óptico de Transmissão ao Vivo", "Alcance de 3,2 km."),
    ("Cyberoptics Options", "optical_capacitor_laser"): ("Laser de Capacitor Óptico", "Dano 2D6; ocupa três espaços."),
    ("Cyberoptics Options", "cyberoptic_eyepatch"): ("Tapa-Olho Ciberóptico", "Duas opções; difícil de identificar com Atenção."),

    ("Cyberaudio", "cyberaudio"): ("Ciberáudio", "Módulo básico de audição com seis espaços de opção."),
    ("Cyberaudio", "spectrum_cyberaudio"): ("Ciberáudio Spectrum", "Modelo antigo; -1 em equilíbrio e +1/+2 em Atenção."),
    ("Cyberaudio", "soviet_cyberaudio"): ("Ciberáudio Soviético", "Apenas dois espaços de opção; 50% de chance de ATR -1."),

    ("Cyberaudio Options", "amplified_hearing"): ("Audição Amplificada", "+1 em Atenção ao usar pistas auditivas."),
    ("Cyberaudio Options", "radio_link"): ("Conexão de Rádio", "Comunicação por rádio em até 1,6 km."),
    ("Cyberaudio Options", "phone_splice"): ("Dispositivo Telefônico", "Comunicação celular completa, apenas em cidades grandes."),
    ("Cyberaudio Options", "scrambler"): ("Misturador", "A transmissão fica incompreensível sem um desmisturador."),
    ("Cyberaudio Options", "bug_detector"): ("Detector de Grampos", "Detecta escutas e bugs a até 3 m; 60% eficaz."),
    ("Cyberaudio Options", "voice_stress_analyser"): ("Analisador de Stress Vocal", "+2 em Percepção Humana e Interrogatório."),
    ("Cyberaudio Options", "sound_editing"): ("Editor de Som", "+2 em Atenção para escutar uma conversa específica."),
    ("Cyberaudio Options", "enhanced_hearing_range"): ("Espectro de Escuta Amplificado", "Permite ouvir frequências supersônicas e subsônicas."),
    ("Cyberaudio Options", "wearman"): ("Wearman", "Sistema de música estéreo."),
    ("Cyberaudio Options", "radar_detector"): ("Detector de Radar", "Emite um bip ao detectar radar e localiza a fonte em 40% dos casos."),
    ("Cyberaudio Options", "homing_tracer"): ("Traçador", "Segue um rastreador a até 1 km de distância."),
    ("Cyberaudio Options", "tight_beam_radio_link"): ("Conexão de Rádio de Segurança", "Permite comunicação de rádio não interceptável dentro da linha de visão."),
    ("Cyberaudio Options", "wide_band_radio_scanner"): ("Escâner de Rádio de Banda Larga", "Capta transmissões em todas as bandas."),
    ("Cyberaudio Options", "micro_recorder_link"): ("Conexão de Microgravador", "Transmite para um gravador corporal ou através dos conectores."),
    ("Cyberaudio Options", "digital_recording_link"): ("Conexão de Gravação Digital", "Transmite sons para um gravador digital."),
    ("Cyberaudio Options", "level_damper"): ("Abafador de Ruído", "Compensação automática de ruído."),
    ("Cyberaudio Options", "fax_plus"): ("Fax+", "Alerta o usuário sobre faxes recebidos."),
}
