"""Bioequipamento, nanotecnologia, biotecnologia e pastilhas."""

DATA = {
    ("BioWare & Nanotech", "grafted_muscle"): ("Enxerto Muscular", "+1 em TIPO CORPORAL por aplicação, até +2."),
    ("BioWare & Nanotech", "muscle_and_bone_lace"): ("Ligamento de Músculos e Ossos", "+2 em TIPO CORPORAL."),
    ("BioWare & Nanotech", "skin_weave"): ("Pele Reforçada", "Confere PB 12 ao corpo inteiro; difícil de notar."),
    ("BioWare & Nanotech", "upgraded_skinweave"): ("Pele Reforçada Aprimorada", "PB 6 a 16, perda de ATR e de quase impossível a mediano de notar."),
    ("BioWare & Nanotech", "lifesaver_skinweave"): ("Pele Reforçada Lifesaver", "+1 ponto de cura por dia."),
    ("BioWare & Nanotech", "enhanced_antibodies"): ("Anticorpos Reforçados", "Aumentam a regeneração em 1 ponto por dia."),
    ("BioWare & Nanotech", "toxin_binders"): ("Antitoxinas", "+4 em testes contra venenos e drogas."),
    ("BioWare & Nanotech", "nanosurgeons"): ("Nanocirurgiões", "Dobram o ritmo natural de regeneração."),
    ("BioWare & Nanotech", "anti_plague_nanotech"): ("Nanotecnologia Antipeste", "+3 contra doenças e agentes de guerra biológica."),
    ("BioWare & Nanotech", "armour_weave"): ("Trama de Blindagem", "+1 TIPO CORPORAL, PB 18 e -1 REF/MA; exige Ligamento de Músculos e Ossos e Pele Reforçada."),
    ("BioWare & Nanotech", "speed_grafts"): ("Enxertos de Velocidade", "+2 MA."),
    ("BioWare & Nanotech", "nanooptical_upgrade"): ("Aprimoramento Nano-Óptico", "+2 em visão noturna."),
    ("BioWare & Nanotech", "nano_groomers"): ("Nanoesteticistas", "+2 a +4 em Aparência e Estilo."),
    ("BioWare & Nanotech", "nitrogen_binders"): ("Fixadores de Nitrogênio", "Reduzem os efeitos da despressurização em até 100%."),
    ("BioWare & Nanotech", "nitrogen_binders_upkeep"): ("Manutenção dos Fixadores de Nitrogênio", "Necessária uma vez a cada três meses."),
    ("BioWare & Nanotech", "advanced_m_b_lace"): ("Ligamento Avançado de Músculos e Ossos", "+1 em TIPO CORPORAL."),
    ("BioWare & Nanotech", "advanced_m_b_lace_3"): ("Ligamento Avançado de Músculos e Ossos +3", "+3 em TIPO CORPORAL."),
    ("BioWare & Nanotech", "alpha_tuffbone_skeletal_enh"): ("Reforço Esquelético TuffBone Alfa", "+1 para levantar e carregar peso e no MTC contra combate corpo a corpo."),
    ("BioWare & Nanotech", "beta_tuffbone_skeletal_enh"): ("Reforço Esquelético TuffBone Beta", "+2 para levantar e carregar peso e no MTC contra combate corpo a corpo; ATR -1."),
    ("BioWare & Nanotech", "hemological_replacement"): ("Substituição Hemológica", "+1 MA e Resistência, +4 minutos sem respirar e -1 contra venenos e doenças."),
    ("BioWare & Nanotech", "neoappendix"): ("Neoapêndice", "+2 em Sobrevivência para encontrar alimento."),
    ("BioWare & Nanotech", "nanoauditory_rebuild"): ("Reconstrução Nanoauditiva", "Inclui Espectro de Escuta Amplificado e Abafador de Ruído."),
    ("BioWare & Nanotech", "sunblocker_sunscreen"): ("Protetor Solar Sunblocker", "Evita queimaduras solares e reduz o risco de câncer de pele."),
    ("BioWare & Nanotech", "neolungs"): ("Neopulmões", "Permitem prender a respiração pelo dobro do tempo normal."),
    ("BioWare & Nanotech", "neural_bridge"): ("Ponte Neural", "Concede ambidestria e elimina a penalidade da mão inábil."),
    ("BioWare & Nanotech", "circulatory_sphincters"): ("Esfíncteres Circulatórios", "+2 em testes de Atordoamento/Choque após um ferimento Grave ou pior."),
    ("BioWare & Nanotech", "poison_glands_teeth"): ("Glândulas de Veneno - Dentes", "Presas naturais que injetam veneno ao morder."),
    ("BioWare & Nanotech", "poison_glands_teeth_i"): ("Glândulas de Veneno - Dentes/Ilegal", "Presas naturais que injetam veneno ao morder."),
    ("BioWare & Nanotech", "poison_glands_hands"): ("Glândulas de Veneno - Mãos", "Podem revestir Estripadores ou Garras com veneno."),
    ("BioWare & Nanotech", "poison_glands_hands_i"): ("Glândulas de Veneno - Mãos/Ilegal", "Podem revestir Estripadores ou Garras com veneno."),
    ("BioWare & Nanotech", "tailored_pheromones_love"): ("Feromônios Sob Medida - Amor", "+1 em Sedução; Filtros Nasais são 60% eficazes."),
    ("BioWare & Nanotech", "tailored_pheromones_gullible"): ("Feromônios Sob Medida - Credulidade", "+1 em Persuasão; Filtros Nasais são 60% eficazes."),
    ("BioWare & Nanotech", "tailored_pheromones_confu"): ("Feromônios Sob Medida - Confusão", "-1 INT e Iniciativa a 1 m; Filtros Nasais são 60% eficazes."),
    ("BioWare & Nanotech", "kaloric_secondary_gut"): ("Intestino Secundário Kaloric", "Armazena alimento para dois dias."),
    ("BioWare & Nanotech", "freezeban_bioconstruct"): ("Bioconstructo Freezeban", "+1 em Sobrevivência e Resistência sob -10 °C."),
    ("BioWare & Nanotech", "quickclot_hemofibrinic_node"): ("Nódulo Hemofibrínico Quickclot", "Trata ferimentos como um estado menos grave; 10% de risco de derrame."),
    ("BioWare & Nanotech", "flashlite_implant"): ("Implante Flashlite", "Brilho sem ofuscamento, semidirecionado, com alcance de 1 m."),
    ("BioWare & Nanotech", "replitech_toxin_screen"): ("Filtro de Toxinas Replitech", "90% de chance de provocar vômito quando uma toxina é ingerida."),
    ("BioWare & Nanotech", "t_maxx_ileocecal_siphon"): ("Sifão Ileocecal T-Maxx", "Permite funcionar sem água por 24 a 48 horas."),
    ("BioWare & Nanotech", "diet_mite"): ("Diet-Mite", "Filtra o que é ingerido e deixa passar apenas o necessário."),
    ("BioWare & Nanotech", "erased_fingerprints"): ("Impressões Digitais Apagadas", "Apaga as impressões digitais."),
    ("BioWare & Nanotech", "altered_fingerprints"): ("Impressões Digitais Alteradas", "Altera permanentemente as impressões digitais."),
    ("BioWare & Nanotech", "alterable_prints"): ("Impressões Digitais Programáveis", "Nanotecnologia programável altera as impressões em 20 segundos."),
    ("BioWare & Nanotech", "altered_retinas"): ("Retinas Alteradas", "Altera permanentemente as retinas."),
    ("BioWare & Nanotech", "programmable_retinas"): ("Retinas Programáveis", "Projeta padrões predefinidos diferentes em 1 minuto."),
    ("BioWare & Nanotech", "altered_dna"): ("DNA Alterado", "Altera o DNA por meio de um retrovírus feito sob medida."),
    ("BioWare & Nanotech", "full_spectrum_booster"): ("Intensificador de Espectro Total", "+4 contra doenças, infecções, venenos e drogas; +2 em Cura."),
    ("BioWare & Nanotech", "muscle_enhancement"): ("Aprimoramento Muscular", "+1 em TIPO CORPORAL."),
    ("BioWare & Nanotech", "chem_weave"): ("Trama Química", "+4 em testes contra agentes químicos."),
    ("BioWare & Nanotech", "thermal_weave"): ("Trama Térmica", "Aumenta a resistência ao calor até 42 °C."),
    ("BioWare & Nanotech", "vac_weave"): ("Trama de Vácuo", "Fortalece o corpo contra descompressão."),
    ("BioWare & Nanotech", "rad_weave"): ("Trama Antirradiação", "Concede 1 PBR de proteção contra radiação."),
    ("BioWare & Nanotech", "reflex_boost"): ("Amplificador de Reflexos", "+1 REF."),
    ("BioWare & Nanotech", "enhanced_sense"): ("Sentido Reforçado", "Aprimora um sentido à escolha."),
    ("BioWare & Nanotech", "ihag_nictating_membrane"): ("Membrana Nictitante IHAG", "Permite enxergar em condições difíceis; substitua a cada 6 a 8 meses."),
    ("BioWare & Nanotech", "sinus_reconstruction"): ("Reconstrução dos Seios da Face", "Equaliza a pressão e suporta 200 m de profundidade."),
    ("BioWare & Nanotech", "nanowear_ozoneshield"): ("OzoneShield Nanowear", "Modificação da Pele Reforçada que protege contra UV."),
    ("BioWare & Nanotech", "antidazzle_nicm"): ("NICM Anti-Ofuscante", "Proteção contra clarões."),
    ("BioWare & Nanotech", "poison_gland"): ("Glândula de Veneno", "Produz veneno."),
    ("BioWare & Nanotech", "water_refiltration_sys"): ("Sistema de Refiltragem de Água", "Filtra e reaproveita água."),
    ("BioWare & Nanotech", "lung_weave"): ("Trama Pulmonar", "Reforça os pulmões para uso de LBM."),
    ("BioWare & Nanotech", "shark_weave_full_body"): ("Trama de Tubarão - Corpo Inteiro", "PB 12 e pode causar 1D6/3* de dano."),
    ("BioWare & Nanotech", "shark_weave_partial"): ("Trama de Tubarão - Parcial", "PB 12 na área escolhida e 1D6/3* de dano."),
    ("BioWare & Nanotech", "thermaskin"): ("Thermaskin", "Isola até 0 °C; provoca suor a partir de 27 °C."),

    ("Biotech", "preparatory_dna_mapping"): ("Mapeamento Preparatório de DNA", "Obrigatório para toda biotecnologia."),
    ("Biotech", "permanent_ref_increase"): ("Aumento Permanente de REF", "Máximo de +1."),
    ("Biotech", "permanent_bod_increase"): ("Aumento Permanente de TIPO CORPORAL", "Máximo de +2."),
    ("Biotech", "permanent_att_increase"): ("Aumento Permanente de ATR", "Máximo de +3."),
    ("Biotech", "permanent_ma_increase"): ("Aumento Permanente de MA", "Máximo de +4."),
    ("Biotech", "reduced_oxygen_demand"): ("Demanda Reduzida de Oxigênio", "Permite respirar em meio a smog."),
    ("Biotech", "uv_resistance"): ("Resistência a UV", "Dispensa protetor solar."),
    ("Biotech", "toughened_skin"): ("Pele Endurecida", "Armadura macia PB 6, indistinguível da pele normal."),

    ("Bioenhancement Tabs", "endurance"): ("Resistência", "Ignora fadiga por 12 horas, dobra a necessidade de alimento e causa 1D3 a 1D6 de dano."),
    ("Bioenhancement Tabs", "ignore_pain"): ("Ignorar Dor", "+4 em Testes de Atordoamento por 12 horas; -2 na sensibilidade tátil."),
    ("Bioenhancement Tabs", "anti_trauma"): ("Antitrauma", "+2 em Testes de Morte por 12 horas."),

    ("RNA Memory Tabs", "skill_1"): ("Perícia +1", "Dura 3 horas; em 1D10, resultado maior que 1 causa -1 na perícia."),
    ("RNA Memory Tabs", "skill_2"): ("Perícia +2", "Dura 3 horas; em 1D10, resultado maior que 2 causa -1 na perícia."),
    ("RNA Memory Tabs", "skill_3"): ("Perícia +3", "Dura 3 horas; em 1D10, resultado maior que 3 causa -1 na perícia."),
}
