"""Cibermembros, opções, mãos, pés e ciberdedos."""

DATA = {
    ("Cyberlimbs", "standard_cyberarm"): ("Ciberbraço", "20/30 PDE, quatro espaços de opção e soco de 1D6."),
    ("Cyberlimbs", "standard_cyberleg"): ("Ciberperna", "20/30 PDE, três espaços de opção e chute de 2D6."),
    ("Cyberlimbs", "artificial_shoulder_mount"): ("Ombros Artificiais", "Permitem montar até dois braços extras; 25 PDE."),
    ("Cyberlimbs", "orbital_crystal_cyberarm"): ("Ciberbraço de Cristal Orbital", "50/60 PDE, quatro espaços de opção e soco de 1D6."),
    ("Cyberlimbs", "orbital_crystal_cyberleg"): ("Ciberperna de Cristal Orbital", "50/60 PDE, três espaços de opção e chute de 2D6."),
    ("Cyberlimbs", "independent_cyberhand"): ("Cibermão Independente", "Esmagamento de 1D10, 7/10 PDE e um espaço de opção."),
    ("Cyberlimbs", "romanova_cyberlegs"): ("Ciberpernas Romanova", "+1 em Aparência e Estilo."),
    ("Cyberlimbs", "supersized_arm"): ("Braço SuperSized", "30/40 PDE, -2 REF, EV +1, dano 2D10/3D6 e PB 20."),
    ("Cyberlimbs", "enable_cyberarm"): ("Ciberbraço Enable", "Modelo antigo; 23/33 PDE e REF -1."),
    ("Cyberlimbs", "enable_cyberleg"): ("Ciberperna Enable", "Modelo antigo; 28/35 PDE, REF -1 e MA -2."),
    ("Cyberlimbs", "soviet_cyberleg"): ("Ciberperna Soviética", "30/40 PDE, chute de 3D10, 5% de falha e dois espaços."),
    ("Cyberlimbs", "soviet_cyberarm"): ("Ciberbraço Soviético", "30/40 PDE, soco de 3D6, esmagamento de 2D10 e 5% de falha."),
    ("Cyberlimbs", "corvette_cyberlegs_basic"): ("Ciberpernas Corvette - Básicas", "+3 MA e +1 em testes de movimento."),
    ("Cyberlimbs", "corvette_cyberlegs_advan"): ("Ciberpernas Corvette - Avançadas", "+8 MA e +2 em testes de movimento."),
    ("Cyberlimbs", "high_speed_maneuvering_system"): ("Sistema de Manobra em Alta Velocidade", "Aprimoramento para o módulo Corvette."),
    ("Cyberlimbs", "speeding_bullet_legs"): ("Pernas Speeding Bullet", "MA 16, salto de 10 m e um espaço livre por perna."),
    ("Cyberlimbs", "sovwear_cyberarm"): ("Ciberbraço SovWear", "30/40 PDE, dano 3D6/6D6, três espaços e disponibilidade UR."),
    ("Cyberlimbs", "sovwear_cyberleg"): ("Ciberperna SovWear", "30/40 PDE, chute de 6D6, dois espaços e disponibilidade UR."),
    ("Cyberlimbs", "cyber_bar_leg"): ("Ciberperna Bar", "Bar embutido."),
    ("Cyberlimbs", "tentacle_arm"): ("Braço-Tentáculo", "Oito tentáculos de 70 cm, 5 PDE cada; ombro com 20 PDE."),
    ("Cyberlimbs", "extendable_tentacle_arm"): ("Braço-Tentáculo Extensível", "Como o anterior, mas os tentáculos se estendem até 150 cm."),

    ("Cyberlimbs Options", "quick_change_mount"): ("Dispositivo de Mudança Rápida", "Permite trocar um cibermembro em um turno."),
    ("Cyberlimbs Options", "hydraulic_rams"): ("Aríete Hidráulico", "30/40 PDE e 3x o dano normal; ocupa um espaço."),
    ("Cyberlimbs Options", "thickened_myomar"): ("Fibra Densa", "25/35 PDE e 2x o dano normal; ocupa um espaço."),
    ("Cyberlimbs Options", "reinforced_joints"): ("Articulações Reforçadas", "+5 PDE."),
    ("Cyberlimbs Options", "microwave_emp_shielding"): ("Escudo Contra Micro-Ondas/PEM", "Reduz a vulnerabilidade do membro a PEM e micro-ondas."),
    ("Cyberlimbs Options", "plastic_covering"): ("Cobertura Plástica", "Disponível em cores, acabamentos transparentes e outros estilos."),
    ("Cyberlimbs Options", "realskinn"): ("RealSkinn", "Faz o membro parecer real; 70% eficaz e difícil de perceber."),
    ("Cyberlimbs Options", "superchrome"): ("Supercromo", "Cobertura metálica de alto brilho."),
    ("Cyberlimbs Options", "armor"): ("Blindagem", "Protege o cibermembro com PB 20."),
    ("Cyberlimbs Options", "leg_boosters"): ("Impulsores de Perna", "+3 m nos saltos; ocupam dois espaços."),
    ("Cyberlimbs Options", "fleshweave"): ("Fleshweave", "Ocupa um espaço de opção; reparos custam +50%. Preço: +20%."),
    ("Cyberlimbs Options", "extra_twist_joint_addition"): ("Articulação Giratória Extra", "+2 em testes atléticos, agarrões e fugas de Arte Marcial. Preço: +30%."),
    ("Cyberlimbs Options", "double_jointed"): ("Articulação Dupla", "+1 em agarrões, imobilizações, estrangulamentos e fugas; ocupa 0,5 espaço."),
    ("Cyberlimbs Options", "locking_joints"): ("Articulações Traváveis", "Exigem um teste de Força 25+ para serem movidas; ocupam 0,5 espaço."),
    ("Cyberlimbs Options", "rotating_joints_360"): ("Articulações Giratórias de 360°", "+1 em fugas e em alguns reparos de TEC; ocupam 0,5 espaço."),
    ("Cyberlimbs Options", "extending_leg_units"): ("Unidades Extensoras de Perna", "Alteram a altura de -30 cm a +90 cm e concedem +1 MA; ocupam dois espaços."),
    ("Cyberlimbs Options", "spiked_limb_cover"): ("Cobertura Espinhosa de Membro", "+1D6 de dano em agarrões e imobilizações."),
    ("Cyberlimbs Options", "tentacle_arm_sheath"): ("Bainha para Braço-Tentáculo", "Esconde os tentáculos, imita um ciberbraço e possui duas aberturas."),

    ("Hands & Feet", "standard_hand"): ("Mão Padrão", "Parece uma mão normal."),
    ("Hands & Feet", "ripper_hand"): ("Mão com Estripadores", "Mão padrão com Estripadores embutidos; dano 1D6+3*."),
    ("Hands & Feet", "hammerhand"): ("Mão Martelo", "O punho com aríete hidráulico causa 1D10 de dano."),
    ("Hands & Feet", "buzzhand"): ("Mão com Serra", "Serra circular elétrica; dano 2D6+2*."),
    ("Hands & Feet", "tool_hand"): ("Mão com Ferramentas", "Os dedos contêm chave de fenda, chave inglesa, furadeira e outras ferramentas."),
    ("Hands & Feet", "grapple_hand"): ("Mão com Agarrador", "Dispara um gancho autopropelido com cabo de 30 m."),
    ("Hands & Feet", "extension_hand"): ("Extensor de Mão", "A mão se estende sobre um membro retrátil de até 1 m."),
    ("Hands & Feet", "spike_hand"): ("Mão com Pregos", "Pregos se estendem pelos dedos; dano 1D6+3 PA."),
    ("Hands & Feet", "modular_hand"): ("Mão Modular", "Escolha quatro ferramentas modulares quaisquer."),
    ("Hands & Feet", "mace_hand"): ("Mão Maça", "Dano 2D6+1/1D10-2 e alcance de 1 m."),
    ("Hands & Feet", "cyberhand_coverings"): ("Coberturas para Cibermão", "Mesma faixa de acabamentos disponível para cibermembros."),
    ("Hands & Feet", "custom_cyberhand"): ("Cibermão Personalizada", "Características variáveis."),
    ("Hands & Feet", "web_hand"): ("Mão com Membranas", "+2 em Natação, +1 a 2 m por turno e dano 1D6*."),
    ("Hands & Feet", "iec_venom_hand"): ("Mão Venenosa IEC", "Quatro agulhas; golpe cortante causa 1D6-1 de dano."),
    ("Hands & Feet", "medical_modular_cyberhand"): ("Cibermão Modular Médica", "Bisturi mono, hipodérmica a ar, grampeador, sonda e outras ferramentas."),
    ("Hands & Feet", "dainamax_grapplefist"): ("Punho-Agarrador Dainamax", "Cabo de 50 m, dois espaços e esmagamento de 2D6+2."),
    ("Hands & Feet", "surveillance_hand"): ("Mão de Vigilância", "Cibermão controlada remotamente."),
    ("Hands & Feet", "drill_hand"): ("Mão-Furadeira", "Causa 3D6 de dano."),
    ("Hands & Feet", "travel_hand"): ("Mão de Viagem", "Quatro opções instaladas nos dedos."),
    ("Hands & Feet", "gouge_master"): ("Gouge Master", "Dano 2D6+3 PA ou 2D6*, dois espaços e cabo com carretel de 20 m."),
    ("Hands & Feet", "lightning_fist"): ("Punho Relâmpago", "Descarga elétrica: Atordoamento -1 ou 2D6+1 de dano."),
    ("Hands & Feet", "standard_foot"): ("Pé Padrão", "Parece um pé normal."),
    ("Hands & Feet", "talon_foot"): ("Pé com Garras", "Lâminas se estendem pelos dedos; dano 1D6*."),
    ("Hands & Feet", "tool_foot"): ("Pé com Ferramentas", "Os dedos contêm chave de fenda, chave inglesa, furadeira e outras ferramentas."),
    ("Hands & Feet", "web_foot"): ("Pé com Nadadeiras", "Dobra a velocidade de natação e concede +3 em Natação."),
    ("Hands & Feet", "grip_foot"): ("Pé Firme", "Projetado para se agarrar melhor; +2 em Escalar."),
    ("Hands & Feet", "spike_heel_foot"): ("Pé com Salto em Ponta", "Salto pontudo para chutes letais; dano 2D6 PA."),
    ("Hands & Feet", "skate_foot"): ("Pé-Patim", "Permite MA 20; use Atletismo ou a perícia Patinação."),
    ("Hands & Feet", "anchoring_cyberfeet"): ("Ciberpés de Ancoragem", "Ancoram o usuário ao solo; quatro usos e dois espaços por pé."),
    ("Hands & Feet", "catspaw_stealth_foot"): ("Pé Furtivo Catspaw", "+1 em Furtividade."),
    ("Hands & Feet", "mini_camera_in_palm"): ("Minicâmera na Palma", "É uma câmera. Simples assim, choom."),

    ("Fingers", "dartgun"): ("Pistola de Dardo", "Alcance de 3 m."),
    ("Fingers", "lockpick"): ("Gazua", "Gazua para fechaduras mecânicas."),
    ("Fingers", "mini_light"): ("Minilanterna", "Feixe de 25 m; baterias custam 1 eb."),
    ("Fingers", "finger_bomb"): ("Dedo-Bomba", "Dano 2D6+3 em um raio de 3 m."),
    ("Fingers", "wirecutters_scissors"): ("Alicate/Tesoura", "Dano 1D6/3."),
    ("Fingers", "mace_sprayer"): ("Esguicho de Gás Mace", "Duas rajadas; -4 REF e Notar por 1D6 turnos."),
    ("Fingers", "quick_change_mount"): ("Dispositivo de Mudança Rápida", "Encaixe de pressionar e girar; modificação custa 20 eb."),
    ("Fingers", "vidcam_plus_option"): ("VidCam com Uma Opção", "IV por 200 eb, Telóptico por 225 eb ou LowLight por 100 eb."),
    ("Fingers", "self_propelled_grenade"): ("Granada Autopropelida", "Alcance de 7 m; 2D6 em um raio de 2 m; recarga custa 25 eb."),
    ("Fingers", "aip_hypo"): ("Hipodérmica AIP", "Quatro doses; recipientes de ar custam 3 eb."),
    ("Fingers", "tracking_device"): ("Dispositivo de Rastreamento", "Alcance de 3 m, dois bugs e transmissor de 3 km."),
    ("Fingers", "lighter"): ("Isqueiro", "Duas horas de combustível; recarga custa 1 eb."),
    ("Fingers", "probe_link"): ("Conexão de Sonda", "Conexão de interface."),
    ("Fingers", "parabolic_microphone"): ("Microfone Parabólico", "Microfone com ampliação de 20x; exige braço completo."),
    ("Fingers", "flasher"): ("Ofuscador", "O alvo testa REF para não ficar cego por 1 minuto; recarga custa 25 eb."),
    ("Fingers", "ir_uv_flashlight"): ("Lanterna IV/UV", "Alcance de 10 m."),
    ("Fingers", "flare"): ("Sinalizador", "Altitude de 150 m e diâmetro de 25 m; recarga custa 15 eb."),
    ("Fingers", "storage_compartment"): ("Compartimento de Armazenamento", "Pequeno espaço interno."),
    ("Fingers", "laser_pointer"): ("Ponteiro Laser", "Alcance de 20 m."),
    ("Fingers", "flesh_mount"): ("Encaixe de Carne", "Permite montar ciberdedos em uma mão de carne."),
    ("Fingers", "one_shot_special"): ("Especial de Um Tiro", "P -2, P, E, 1D6 (5 mm), 1, 1, ST, alcance de 20 m."),
    ("Fingers", "ballpoint_finger"): ("Dedo-Caneta", "Caneta esferográfica à prova de vazamentos."),
    ("Fingers", "cyberfinger_oxygen_tank"): ("Tanque de Oxigênio em Ciberdedo", "Fornece 30 segundos de oxigênio."),
    ("Fingers", "screwdriver"): ("Chave de Fenda", "Ciberdedo com chave de fenda motorizada."),
    ("Fingers", "wrench"): ("Chave Inglesa", "Ciberdedo com chave inglesa ajustável."),
    ("Fingers", "drill"): ("Furadeira", "Ciberdedo com furadeira ajustável."),
    ("Fingers", "soldering_iron"): ("Ferro de Solda", "Ciberdedo com ferro de solda elétrico."),
    ("Fingers", "socket_wrench"): ("Chave de Soquete", "Ciberdedo motorizado com chave de soquete ajustável."),
    ("Fingers", "tentacle_finger"): ("Dedo-Tentáculo", "Tentáculo de 10 cm."),
    ("Fingers", "extendable_tentacle"): ("Tentáculo Extensível", "Tentáculo de 30 cm; exige cibermão."),
}
