"""Modificações exóticas, pacotes e chipware."""

DATA = {
    ("Exotic Modifications", "minor_facial_modification"): ("Modificação Facial Menor", "Alterações nos olhos, orelhas, nariz e outras feições."),
    ("Exotic Modifications", "major_facial_modification"): ("Modificação Facial Maior", "Alterações extensas nas feições."),
    ("Exotic Modifications", "muzzle_short"): ("Focinho Curto", "Semelhante ao focinho de um urso ou tigre."),
    ("Exotic Modifications", "muzzle_long"): ("Focinho Longo", "Semelhante ao focinho de um cão ou cavalo."),
    ("Exotic Modifications", "mandibles_extended"): ("Mandíbulas Estendidas", "Mandíbulas preênseis; dano 1D6*."),
    ("Exotic Modifications", "natural_fangs"): ("Presas Naturais", "Dano de mordida 1D6*."),
    ("Exotic Modifications", "natural_claws"): ("Garras Naturais", "-3 em testes de manipulação; dano 1D6*."),
    ("Exotic Modifications", "retractable_claws"): ("Garras Retráteis", "Dano 1D6*."),
    ("Exotic Modifications", "scratchers"): ("Arranhadores", "PH reduzida graças à implantação hospitalar."),
    ("Exotic Modifications", "rippers"): ("Estripadores", "PH reduzida graças à implantação hospitalar."),
    ("Exotic Modifications", "short_tail"): ("Cauda Curta", "Cauda de coelho ou semelhante."),
    ("Exotic Modifications", "tail"): ("Cauda", "Móvel, porém fraca; exerce cerca de 1,4 kg de força."),
    ("Exotic Modifications", "combat_tail"): ("Cauda de Combate", "Fortemente musculosa; dano 1D6 mais o modificador de dano."),
    ("Exotic Modifications", "stinger_tail"): ("Cauda com Ferrão", "Ferrão injetor de veneno; dano 1D6* + modificador + droga/toxina."),
    ("Exotic Modifications", "digitgrade_legs"): ("Pernas Digitígradas", "Pernas com três articulações; +1 MA com cauda e -2 MA sem cauda."),
    ("Exotic Modifications", "fur_scales_skinchange"): ("Pelos/Escamas/Mudança de Pele", "10% de chance de câncer."),
    ("Exotic Modifications", "heavy_scales"): ("Escamas Pesadas", "PB 12 e 10% de chance de câncer."),
    ("Exotic Modifications", "exoskeleton"): ("Exoesqueleto", "PB 18, MA e REF -2 e 10% de chance de câncer."),
    ("Exotic Modifications", "frame_alteration"): ("Alteração de Estrutura Corporal", "Muda o tamanho em até 25% em relação ao corpo original."),
    ("Exotic Modifications", "muscle_pouch"): ("Bolsa Muscular", "Musculatura lombar para sustentar caudas ou tentáculos."),

    ("Exotic Package", "katnip_feline"): ("KatNip - Felino", "Olhos fendidos, orelhas pontudas, cauda, Pele Sintética e Arranhadores."),
    ("Exotic Package", "rodent"): ("Roedor", "Orelhas e olhos ampliados, nariz curto e Pele Sintética."),
    ("Exotic Package", "rabbit"): ("Coelho", "Orelhas e cauda de coelho, nariz curto e bigodes."),
    ("Exotic Package", "reptile"): ("Réptil", "Sem orelhas, língua longa, olfato reforçado, presas e Pele Sintética."),
    ("Exotic Package", "elf"): ("Elfo", "Orelhas pontudas, rosto fino e sobrancelhas arqueadas."),
    ("Exotic Package", "dwarf_halfling"): ("Anão/Halfling", "Estrutura mais baixa e robusta, MA -2 e feições mais largas."),
    ("Exotic Package", "ork_goblin"): ("Ork/Goblin", "Feições largas, braços longos, presas e Pele Sintética."),
    ("Exotic Package", "troll_ogre"): ("Troll/Ogro", "Feições largas, presas, altura maior, Enxerto Muscular e Ligamento de Músculos e Ossos."),
    ("Exotic Package", "fishman"): ("Homem-Peixe", "Guelras, Pele Sintética, membranas natatórias e Holo-Contatos personalizados."),
    ("Exotic Package", "zark_nartanq_graftable"): ("Enxerto Zark Nartanq", "Presas, Garras, cauda, Pele Reforçada, Ligamento de Músculos e Ossos e mais."),
    ("Exotic Package", "bear_package"): ("Pacote Urso", "Focinho, presas, garras, pelos, altura maior e Enxerto Muscular."),
    ("Exotic Package", "the_superman"): ("O Super-Homem", "O futuro da humanidade por meio de nano e bioequipamento."),
    ("Exotic Package", "bigkatt"): ("BigKatt", "Focinho, presas, garras, cauda, pernas digitígradas e pelos."),
    ("Exotic Package", "slight_buggy"): ("Levemente Insetoide", "Olhos de inseto, antenas, Pele Sintética escamosa e ciberópticos."),
    ("Exotic Package", "franz_kafka_bughouse"): ("Bughouse Franz Kafka", "Como o pacote anterior, mais mandíbulas, exoesqueleto e Arranhadores."),
    ("Exotic Package", "merman"): ("Tritão", "Guelras, mudança de pele, cauda de peixe, Holo-Contatos personalizados e sonar."),
    ("Exotic Package", "sharkman"): ("Homem-Tubarão", "Guelras, sonar, Pele Reforçada, mudança de pele, focinho e mais."),
    ("Exotic Package", "lupaform_minor_package"): ("Pacote LupaForm Menor", "Orelhas pontudas, nariz e olhos caninos, presas e Pele Sintética."),
    ("Exotic Package", "lupaform_major_package"): ("Pacote LupaForm Maior", "Como o Menor, mais focinho, cauda, pernas digitígradas e pelos."),
    ("Exotic Package", "humanisaurus_rex_dragon"): ("Humanisaurus Rex - Dragão", "Focinho curto, presas, cauda e escamas."),
    ("Exotic Package", "playbeing_addition"): ("Adição Playbeing", "ATR aumentado, Amplificador Tátil, Chip de Comportamento e mais."),

    ("Chipware", "aptr_reflex_chips"): ("Chips de Reflexo", "Chips de perícias baseadas em reflexo e técnica."),
    ("Chipware", "mram_memory_chips"): ("Chips de Memória", "Chips de INT, outras perícias cognitivas e bancos de dados."),
    ("Chipware", "mo_chips"): ("Chips M.O.", "Fornecem uma resposta de sim ou não com um teste de INT 15+."),
    ("Chipware", "courier_chip"): ("Chip Mensageiro", "Grava dados no cérebro do usuário."),
    ("Chipware", "security_chips"): ("Chips de Segurança", "Chips que podem ser apagados ou destruídos."),
    ("Chipware", "digi_tone_id"): ("Identificador Digi-Tone", "Usado com ciberáudio para reconhecer números telefônicos."),
    ("Chipware", "special_operative_chip"): ("Chip de Agente Especial", "+1 em Idioma, Geografia e uma outra perícia.", "Inclui +1 em uma perícia situacional adicional."),
    ("Chipware", "poser_impersonation_chip"): ("Chip de Imitação Poser", "Conhecimento Específico do alvo +2 e Atuação +1."),
    ("Chipware", "photomemory_ram_chip"): ("Chip RAM de Memória Fotográfica", "Teste de INT +2, dificuldade 15+, para recuperar uma lembrança específica."),
    ("Chipware", "memory_compression"): ("Compressão de Memória", "Distribui três níveis entre até três perícias.", "Distribui um total de +3 entre até três perícias."),
    ("Chipware", "programmable_chipware"): ("Chipware Programável", "Fornece conhecimento básico de um procedimento."),
    ("Chipware", "mind_games"): ("Jogos Mentais", "Mais de 300 jogos disponíveis."),
    ("Chipware", "business_trip_chip"): ("Chip de Viagem de Negócios", "+1 em Idioma, Cultura e Aparência e Estilo ou Direito Empresarial.", "Escolha +1 em Aparência e Estilo ou +1 em Direito Empresarial para o destino."),
    ("Chipware", "tourism_chip"): ("Chip de Turismo", "+1 em Idioma, Cultura e Conhecimento Geral."),
    ("Chipware", "space_chip"): ("Chip Espacial", "Sobrevivência Espacial +2 e Cultura Highrider +1."),
    ("Chipware", "maximum_lover_chip"): ("Chip Amante Máximo", "+2 em Sedução."),
    ("Chipware", "stress_chip"): ("Chip de Stress", "+1 COOL para moral e +1 EMP em interações."),
    ("Chipware", "adrenaline_endorphin_surge"): ("Surto de Adrenalina/Endorfina", "Ignora dor e exaustão; +1 TIPO CORPORAL três vezes em 24 horas."),
    ("Chipware", "increased_neural_feedback"): ("Feedback Neural Aumentado", "Reduz pela metade o tempo para chipar; queima em 24 horas.", "Útil apenas com chips APTR; torna-se inutilizável após cerca de 24 horas de uso."),
    ("Chipware", "ambidexterity_chip"): ("Chip de Ambidestria", "Torna o usuário ambidestro.", "Não pode ser comprado novamente para repetir o mesmo efeito."),
    ("Chipware", "independent_action_chip"): ("Chip de Ação Independente", "Ação independente para cada braço e dois ciberópticos.", "Exige Ambidestria. Com dois ciberópticos, um segundo chip permite ação independente para cada braço."),
    ("Chipware", "deathtrance"): ("Transe de Morte", "Leva 1 a 3 minutos para entrar; exige Técnica Médica 25+ para detectar vida.", "Induz um transe semelhante à morte para ocultação; utilidade limitada durante primeiros socorros."),
    ("Chipware", "redundancy_loop"): ("Loop de Redundância", "Falha em um momento crucial em 50% a 75% dos casos.", "Variante APTR instável, feita para falhar justamente quando mais importa."),
    ("Chipware", "fish_n_chips"): ("Fish N' Chips", "Dispositivo de controle de apetite.", "Biochip dietético para suprimir o apetite, comum na moda e em casos de transtorno alimentar."),
    ("Chipware", "visual_recognition_chips"): ("Chips de Reconhecimento Visual", "INT + chip + 1D10 + perícia; perfis Tec, Corp, Rocker e outros.", "Todos os testes usam INT + chip + 1D10 + Conhecimento Específico aplicável. Perfis chegam a +3 e exigem Times Square Plus."),
    ("Chipware", "techie_visual_rec_chip"): ("Chip Visual de Técnico", "Identifica circuitos, peças, ferramentas, fabricantes e números de série.", "Máximo de +3; a validade dos dados depende da data de fabricação."),
    ("Chipware", "corporate_visual_rec_chip"): ("Chip Visual Corporativo", "Reconhece executivos, documentos e operações corporativas, com biografias limitadas.", "Perfil corporativo até +3, com custos fixos de 50/100/150 eb. Oficialmente exclusivo de corporações; cópias do mercado negro existem."),
    ("Chipware", "police_visual_rec_chip"): ("Chip Visual Policial", "Identifica visualmente criminosos e licenças.", "Inclui boletins diários ou semanais e referências de procurados; atualizações podem custar até 2,5x o valor-base."),
    ("Chipware", "military_visual_rec_chip"): ("Chip Visual Militar", "Reconhece uniformes, unidades e silhuetas de armas e veículos.", "Máximo de +3; custa 3x o valor normal e deve ser substituído todo ano. Chips com mais de dois anos valem metade."),
    ("Chipware", "rocker_visual_rec_chip"): ("Chip Visual de Rocker", "Reconhece músicas e instrumentos e exibe partituras no ciberóptico.", "Bancos de imagens para caça-talentos e executivos exigem atualização anual."),
    ("Chipware", "secretarial_visual_rec_chip"): ("Chip Visual de Secretariado", "Cruza contatos, agendas, registros e grandes arquivos telefônicos."),
    ("Chipware", "somaware_sleep_chip"): ("Chip de Sono SomaWare", "Sono normal; após 15 usos, teste COOL 15+ para dormir.", "Não induz coma profundo. Após 15 usos, a cada dois usos adicionais faça um teste de COOL contra dependência; Resistência ou Resistência a Tortura/Drogas pode modificar o teste."),
    ("Chipware", "navigation_orientation_chip"): ("Chip de Navegação/Orientação", "Exige Dispositivo Telefônico ou Conexão de Rádio; precisão de 5 m."),
    ("Chipware", "major_city_map"): ("Mapa de Grande Cidade", "Mapa topográfico; exige Receptor de Vídeo ou Videotela Subcutânea."),
    ("Chipware", "crypto_chips"): ("Criptochips", "Código de substituição por palavras gerado aleatoriamente."),
    ("Chipware", "stutter_chipping"): ("Chip de Hesitação", "Impede disparos contra aliados designados por um turno."),
    ("Chipware", "weaponmasters_mart_chip"): ("Chip de Arte Marcial Weaponmasters", "Arasaka-Te e Thamoc disponíveis, até +3.", "Os perfis Weaponmasters incluem as formas Arasaka-Te e Thamoc."),
    ("Chipware", "auditory_recognition_chips"): ("Chips de Reconhecimento Auditivo", "Exigem Audição Amplificada e Editor de Som; máximo de +2."),

    ("Behaviour Chips", "james_bond"): ("James Bond", "COOL +1."),
    ("Behaviour Chips", "xarghis_khan"): ("Xarghis Khan", "EMP 1 e COOL 10."),
    ("Behaviour Chips", "perfect_soldier"): ("Soldado Perfeito", "COOL +3, máximo 11; EMP -2, mínimo 1."),
    ("Behaviour Chips", "kick_ass"): ("Quebra-Tudo", "COOL +2, EMP -2 e agressividade aumentada."),
    ("Behaviour Chips", "sunny_day"): ("Dia Ensolarado", "Provoca felicidade e concede +4 contra Intimidação."),
}
