"""Memória de tradução das notas do catálogo de armas."""


NOTES_PT = {
    "weapon_astra_style_6": "Arma de reserva espanhola, comum e barata, feita de polímero e carregada com projéteis plásticos fragmentários de 5mm.",
    "weapon_budgetarms_c_13": "Pistola automática leve usada como arma de apoio, segunda arma ou 'arma de mulher'.",
    "weapon_dai_lung_cybermag_15": "Cópia barata de Hong Kong, muito usada por Boosters e pela escória das ruas.",
    "weapon_federated_arms_impact": "Pistola de baixo calibre com dez tiros e confiabilidade incomum.",
    "weapon_federated_arms_x_22": "Arma de polímero de tiro único, vendida em 13 cores. O modelo de 6mm custa 50-150eb; a versão sem cápsula de .22 causa 1D6 e custa 25-50eb.",
    "weapon_federated_arms_x_38": "Pistola automática barata de .38 sem cápsula.",
    "weapon_towa_manufacturing_type_12_police_pistol": "Arma curta padrão da polícia japonesa. A versão smartgun concede PA +5 e custa 810eb.",
    "weapon_arasaka_wsa_autopistol": "Arma curta padrão das tropas e dos executivos da Arasaka.",
    "weapon_budgetarms_c_41": "Pistola de grande calibre, dez tiros e boa confiabilidade.",
    "weapon_budgetarms_laser_niner": "Mira laser integral. Configuração padrão J/15/3; com o pente de assalto, S/35/20.",
    "weapon_beretta_m97p": "Mira laser integral. Usa munição Plasticase.",
    "weapon_ccmmc_goaxing_xiuxi_cm_3": "A arma mais potente que um civil pode possuir legalmente na China continental; indisponível fora do país.",
    "weapon_colt_alpha_omega_competition_pistol_45_acp": "Pode receber um sistema de mira Nikon COT por mais 3.900eb.",
    "weapon_colt_alpha_omega_competition_pistol_10mm": "Pode receber um sistema de mira Nikon COT por mais 3.900eb.",
    "weapon_colt_enforcement_10_sidearm_basic": "O smartchip acrescenta 550eb ao preço.",
    "weapon_colt_enforcement_10_sidearm_camouflaged": "O smartchip acrescenta 550eb ao preço.",
    "weapon_dai_lung_streetmaster": "Outra arma barata da Dai Lung, feita para as ruas.",
    "weapon_fn_browning_3_spot_machine_pistol": "Dispara uma rajada de três tiros a cada acionamento do gatilho.",
    "weapon_federated_arms_x_9mm": "Arma curta robusta, usada pelas milícias estaduais dos Estados Unidos.",
    "weapon_fashion_gun_9": "Faixa de preço: 35-40eb. Esvaziar o pente derrete a cobertura do cano e emperra a arma permanentemente.",
    "weapon_goncz_taurus_pistol": "Faixa de preço: 200-275eb. A versão de tiro seletivo aparece como item separado.",
    "weapon_goncz_taurus_pistol_selective_fire": "Faixa de preço: 300-400eb. Aceita pentes de 15 ou 30 tiros; CdT 2/10.",
    "weapon_glock_thirty_machine_pistol": "Tiro único seletivo ou rajada de três tiros. Aceita o pente padrão de 20 tiros ou o pente de 30 tiros.",
    "weapon_hammer_m_11_bolt_pistol": "A blindagem vale 1/4; o dano que atravessa é reduzido à metade. Usa munição com cápsula.",
    "weapon_imi_gamad": "PA +1 com a mira laser. Existe versão smartgun. O pente estendido de 15 tiros custa 35eb e muda o ocultamento para J.",
    "weapon_kang_tao_type_97": "Pistola compacta de serviço, com armação de polímero, fabricada pela Kang Tao.",
    "weapon_leroi_maxi_10": "Pistola 10mm de grande capacidade voltada ao mercado profissional de segurança.",
    "weapon_militech_arms_avenger": "Arma curta de grande calibre, confiável e padrão da Militech.",
    "weapon_militech_black_widow_flechette_pistol": "Cada cartucho contém dez flechetes e se espalha por um metro a média distância. Cada acerto causa 1/2D6; a blindagem é reduzida à metade. Usa munição com cápsula.",
    "weapon_militech_silver_shadow_flechette_pistol": "Cada cartucho contém seis flechetes e se espalha por meio metro a média distância. Cada acerto causa 1D6/3; a blindagem é reduzida à metade. Usa munição com cápsula.",
    "weapon_nomad_357_magnum_autoloader": "Cargas quentes padrão causam 3D6+1. Usa munição com cápsula.",
    "weapon_nomad_357_magnum_revolver": "Inclui três clipes de meia-lua com dois tiros cada. Cargas quentes padrão causam 3D6+1. Usa munição com cápsula.",
    "weapon_sci_fi_starrior_4": "Pistola chamativa de quatro tiros para compradores que colocam estilo em primeiro lugar.",
    "weapon_stein_wasserman_tri_star_revolver": "Dispara munição de espingarda .410: chumbo, balote ou carga Tri-Plex. A mira integral projeta o ponto de visada e o círculo de dispersão.",
    "weapon_sternmeyer_p_41_autoloading_pistol": "Pistola automática europeia de serviço, conhecida pela confiabilidade.",
    "weapon_stolbovoy_st_2_pistol": "Comum na União Soviética e no Leste Europeu, mas rara nos EUA. Nas tabelas FNFF, armas Stolbovoy só emperram com resultado 1. A versão smartchipped custa 850eb.",
    "weapon_surprising_stranger": "Faixa de preço: 15-50eb. Pepperbox de quatro tiros, recarregada pela boca à razão de um cartucho por turno de combate.",
    "weapon_teen_dreem": "Pode disparar em automático. Há 60% de chance de a arma derreter durante fogo automático.",
    "weapon_texas_arms_model_351_gyrojet_pistol": "Comum na Lua, mas raramente vista na Terra.",
    "weapon_towa_manufacturing_type_13_police_pistol": "Sistema smartgun disponível para policiais por 800eb; PA +4.",
    "weapon_towa_manufacturing_type_14_pistol": "O modelo padrão dispara rajadas de três tiros ou em automático. A versão para oficiais inclui smartgun, tem PA +4 e custa 820eb.",
    "weapon_tsunami_express_racegun": "Pistola eletrotérmica de competição com mira Zeiss-Nikon COT integral. Cinquenta munições custam 50eb e a bateria de 50 disparos custa 10eb. Uma empunhadura de 125eb muda o ocultamento para J e a PA para +2; o compensador impede o uso de silenciador.",
    "weapon_wondernines": "Pistolas modernas genéricas de serviço em 9mm sem cápsula. A capacidade é 14+1D6 e o preço é 240eb mais dez vezes o mesmo resultado do dado.",
    "weapon_budgetarms_auto_3": "Em falha crítica ou pane, há 10% de chance de a arma explodir e causar 2D6 no braço do atirador.",
    "weapon_dai_lung_magnum": "Se emperrar ou sofrer falha crítica, há 60% de chance de ferir o atirador e causar 2D6+1 no braço.",
    "weapon_espinoza_one_shot": "Em pane ou falha de disparo, há 60% de chance de a arma explodir e causar 2D6+1.",
    "weapon_malorian_arms_heavy_flechette_pistol": "A blindagem vale 1/4, mas o dano permanece normal. Exige a pulseira de segurança codificada do dono ou um soquete no pulso. Pentes descartáveis custam 14eb.",
    "weapon_mustang_arms_mark_ii": "Usa pente de 12 ou 20 tiros. Em ambiente sujo, a confiabilidade cai para C após um dia sem limpeza e perde outro nível a cada 24 disparos sem limpeza.",
    "weapon_nova_model_338_citygun": "Usa cassetes descartáveis de sete tiros. O cassete vazio custa 5eb, a caixa de munição custa 15eb e o cassete carregado custa 7eb.",
    "weapon_nova_model_757_cityhunter": "Pistola automática com tambor e mira laser integral. O tambor pode ser completado cartucho a cartucho ou trocado como tubo descartável.",
    "weapon_stein_wasserman_bi_power_handcannon_44_magnum": "Um dos dois canos da Bi-Power. A arma completa tem ocultamento S para usuários com COR abaixo de 8.",
    "weapon_stein_wasserman_bi_power_handcannon_45_acp": "Um dos dois canos da Bi-Power. A arma completa tem ocultamento S para usuários com COR abaixo de 8.",
    "weapon_sternmeyer_p_35": "Pistola automática pesada europeia para forças policiais e militares.",
    "weapon_tsunami_arms_raimei_ramjet_pistol": "Preço da versão smartchipped; a variante COT custa 3.200eb. Dano: 5D6 em Curta, 6D6+3 em Média, 7D6 em Longa e 7D6+1 em Extrema. O PA da blindagem é triplicado e o dano penetrante é dobrado.",
    "weapon_454_magnum_disposable": "Arma de reserva não recarregável com dois canos sobrepostos. Puxar a lingueta ativa a bateria selada.",
    "weapon_ameritech_magnum": "Pistola automática Magnum de armação grande, voltada ao mercado americano.",
    "weapon_armalite_44": "Automática muito pesada apresentada no Livro Básico de Cyberpunk 2020.",
    "weapon_colt_amt_model_2000": "Pistola automática grande e potente, carregada com munição de 12mm sem cápsula.",
    "weapon_constitution_arms_multi_ammunition_pistol": "Revólver com munição proprietária e encapsulada. O seletor permite escolher entre cargas letais e não letais antes do disparo.",
    "weapon_federated_arms_454_da_super_chief": "Revólver de ação dupla que usa munição com cápsula.",
    "weapon_malorian_arms_3516": "Arma personalizada para Johnny Silverhand. A ciberinterface direta trava o ciberbraço do usuário enquanto ela dispara.",
    "weapon_militech_477_boomer_buster": "Com a escora aberta ou ao usar um ciberbraço, PA +1 e ocultamento J; nas demais situações, PA -1 e ocultamento S.",
    "weapon_nomad_44_magnum_revolver": "Usa munição com cápsula.",
    "weapon_nova_arms_stallone_357_plasmatic_magnum": "Revólver eletrotérmico Plasmatic que usa munição com cápsula.",
    "weapon_nova_arms_bronson_41_plasmatic_magnum": "Revólver eletrotérmico Plasmatic que usa munição com cápsula.",
    "weapon_nova_arms_eastwood_44_plasmatic_magnum": "Revólver eletrotérmico Plasmatic que usa munição com cápsula.",
    "weapon_nova_arms_arno_454_plasmatic_magnum": "Revólver eletrotérmico Plasmatic que usa munição com cápsula.",
    "weapon_royal_enfield_ordnance_spitfire_12mm_battle_pistol": "A versão smartchipped custa 700eb. A CdT padrão é 1; versões S&S e SAS permitem disparos duplos com CdT 2.",
    "weapon_federated_arms_tech_assault": "Submetralhadora de 30 tiros com modos semiautomático/automático de CdT 10/30.",
    "weapon_federated_arms_tech_assault_ii": "Versão aprimorada da Tech-Assault, com maior capacidade e mecanismo automático melhorado.",
    "weapon_heckler_koch_mpk_9": "Submetralhadora compacta de 9mm para segurança e proteção aproximada.",
    "weapon_militech_mini_gat_machine_carbine": "Carabina Gatling eletrônica de cinco canos, com pente helicoidal de 120 tiros e bateria recarregável no próprio pente.",
    "weapon_setsuko_arasaka_pms_sub_machine_gun": "A versão smartchipped custa 1.150eb.",
    "weapon_suranam_machine_pistol": "Aceita pentes de 25 ou 50 tiros. Em falha crítica, há 75% de chance de todos os cartuchos restantes detonarem e causarem 2D6 no braço do atirador.",
    "weapon_uzi_miniauto_9": "Arma de segurança feita inteiramente de polímero, com pente elétrico rotativo e gatilho ajustável.",
    "weapon_arasaka_wma_minami_10": "A versão com silenciador integral custa mais 350eb e muda a PA para -1 e o ocultamento para S.",
    "weapon_beretta_1010_machine_pistol": "A configuração básica usa pente de 30 tiros. Um pente menor de 15 tiros pode ser instalado quando a cobertura do cano é removida.",
    "weapon_beretta_m_24_advanced_submachine_gun": "Submetralhadora padrão da Interpol, com smartlink integral e compensador de recuo. A versão smartchipped custa 1.250eb.",
    "weapon_heckler_koch_mp_2013": "Atualização da MP-5K, com construção em compósito e silenciador integral.",
    "weapon_imi_gamdaii": "Dois pentes independentes. Inclui lançador de 25mm/espingarda 10: ArPes, PA 0, capacidade 1, CdT 1, C, alcance 100m.",
    "weapon_malorian_arms_sub_flechette_gun": "Cada cartucho sem cápsula lança seis penetradores. Role 1D6 para o número de acertos; cada um causa 1D6 e reduz a blindagem a 1/4 do PA.",
    "weapon_militech_10_submachine_gun": "Causa 2D6+3 em 10mm ou 2D6+2 com o kit intercambiável de .45 ACP.",
    "weapon_militech_viper_submachinegun": "Submetralhadora de operações especiais. O silenciador opcional custa 150eb e reduz a PA em 1.",
    "weapon_mustang_arms_ars_5sc_submachinegun": "A versão smartchipped custa 1.200eb. Versão camuflada: 650eb; luneta +100eb, designador laser +100eb e silenciador +50eb.",
    "weapon_sten": "Preço aproximado; alcance listado de 50-100m. Pode usar .22 LR (1D6), 9mm Parabellum (2D6+1), .357 Magnum (2D6+3) ou 12mm sem cápsula (4D6+1).",
    "weapon_stolbovoy_sts_submachinegun": "A versão smartchipped custa 1.200eb.",
    "weapon_ccmmc_tuzi_7": "Modelo de exportação acabado; custa 500 yuan, aproximadamente 125eb.",
    "weapon_chadran_arms_city_reaper": "Inclui espingarda sob o cano: ESP, PA -1, 4D6 (calibre 12), capacidade 10, CdT 3, C, alcance 50m.",
    "weapon_heckler_koch_mpk_11": "Submetralhadora pesada compacta de 12mm baseada no mecanismo MPK.",
    "weapon_heckler_koch_mpk_2020_smg": "A PA já inclui a mira laser integral.",
    "weapon_ingram_mac_14": "Submetralhadora pesada compacta e de alta cadência, descendente da série MAC.",
    "weapon_sternmeyer_smg_21": "PA 0 com a coronha aberta e -1 com ela recolhida. Modos de rajada de três tiros e automático, CdT 3/15.",
    "weapon_arasaka_wcaa_rapid_assault_shot_12": "Espingarda de combate seletiva da Arasaka, com modos de tiro único e automático.",
    "weapon_ccmmc_qi_15": "Custa 600 yuan, aproximadamente 150eb. Disponível apenas para a polícia militar chinesa.",
    "weapon_constitution_arms_hurricane_assault_weapon": "Espingarda de assalto seletiva, com rajadas de quatro tiros e fogo automático.",
    "weapon_enfield_ubichi_lastchance": "Espingarda compacta concebida como uma poderosa arma de último recurso.",
    "weapon_luigi_franchi_p_16": "Espingarda de combate seletiva, com rajadas de três tiros e fogo automático.",
    "weapon_luigi_franchi_king_buck_multi_magnum": "Os quatro canos podem disparar separadamente ou juntos. Disparar todos exige ciberbraço com COR 11+; caso contrário, causa 2D6 no braço do atirador.",
    "weapon_metacorp_warhammer_assault_shotgun": "Chumbo #00: 4D6+3; HE: 4D6 em raio de 0,5m; balote penetrador: 4D6+2 AP, divide a blindagem pela metade e causa x1,5 contra alvos sem blindagem.",
    "weapon_military_m_12_close_assault_weapon": "Espingarda automática militar com pente rotativo e seletor de munição. Escolher outro tipo já carregado reduz a CdT para 1 naquele disparo.",
    "weapon_militech_bulldog_compact_assault_shotgun": "Espingarda de combate calibre 12, seletiva, com indicador laser do padrão de dispersão. O smartgun de fábrica custa mais 500eb.",
    "weapon_militech_crusher_ssg": "PA -1 a 12m e -3 a 25m. Causa 3D6 em curta distância e 1D6+2 em média; é ineficaz além de 25m.",
    "weapon_militech_military_police_shotgun": "O segundo ocultamento vale com a coronha dobrada e muda a PA para -1. A versão calibre 10 não tem coronha dobrável e causa 5D6.",
    "weapon_mustang_arms_close_control_20": "Bullpup compacta calibre 20 para combate próximo; aceita chumbo, balotes, bastões antimotim e flechetes.",
    "weapon_mustang_arms_raider_riot_shotgun": "Usa o tubo padrão de cinco tiros ou a extensão de nove tiros.",
    "weapon_sternmeyer_stakeout_10": "Espingarda leve calibre 12 usada por departamentos de polícia e forças de segurança.",
    "weapon_tsunami_arms_ragnarok_close_assault_weapon": "Espingarda eletrotérmica de assalto próximo, com dois canos reciprocantes, compensação de recuo Hydroshock e baterias na coronha.",
    "weapon_akr_20_medium_assault": "Usa munição com cápsula.",
    "weapon_arasaka_waa_bullpup_assault_weapon": "Smartchipped e equipada com mira óptica integral. Também aceita pente de cinco tiros.",
    "weapon_ccmmc_jinhua_m_9": "Custa 500 yuan, aproximadamente 125eb. Disponível apenas na China.",
    "weapon_chadran_arms_jungle_reaper": "Sistema de dois canos sobrepostos. A arma pesada de 25mm sob o cano tem PA -2, dano variável, capacidade 6, CdT 2, C e alcance 200m.",
    "weapon_colt_m_18_assault_weapon": "Mira óptica de aquisição rápida concede PA +1 ao mirar. Acabamento camuflado custa 850eb; smartchip acrescenta 750eb.",
    "weapon_darra_polytechnic_m_9_assault_rifle": "Configuração padrão: PA 0 e ocultamento N; coronha lateral dobrada: PA -1 e ocultamento S. Munição de ponta oca dobra o PA da blindagem e multiplica o dano penetrante por 1,5; munição comum causa 4D6. Cem cartuchos de ponta oca custam 45eb no Círculo do Pacífico.",
    "weapon_fn_ral_heavy_assault_rifle": "Com a coronha aberta, PA -1 e ocultamento N; com a coronha recolhida, PA -2 e ocultamento S.",
    "weapon_federated_arms_light_assault_15": "A versão smartchipped custa 700eb. Inclui interface smartgun e mira óptica. Em rajada de três tiros, a PA passa a +1.",
    "weapon_fabrica_de_armes_m_2012": "Calibre básico 6,5x45mm sem cápsula. Pode receber canos para 6,2x39mm soviético (5D6+3), 7,62mm OTAN (6D6+2) ou 7,5mm curto francês (6D6+1). Inclui mira laser-reflex Knipfler & König 2x.",
    "weapon_kalashnikov_a_80_heavy_assault_rifle": "Fuzil de assalto pesado e robusto, descendente da família Kalashnikov.",
    "weapon_militech_dragon_light_assault_weapon": "Arma de assalto leve e compacta da linha de infantaria Militech.",
    "weapon_militech_m_31a1_advanced_infantry_combat_weapon": "Sistema sobreposto com lança-granadas integral de 25mm: LG, PA -1, ocultamento -, disponibilidade -, dano variável, capacidade 4, CdT 2, C e alcance 150m.",
    "weapon_militech_mk_iv_assault_weapon_revised": "O cano de troca rápida alterna entre 6,5mm Hybrid, dano 6D6-1, e 5,56mm, dano 5D6.",
    "weapon_militech_ronin_light_assault": "Fuzil de assalto leve e confiável, muito usado por forças corporativas e militares.",
    "weapon_royal_enfield_ordnance_liquid_propellant_assault_rifle_lpa1": "Usa dois pentes helicoidais de 45 tiros. Velocidades: Baixa/antimotim 2D6+1, Média/urbana 4D6 e Alta/combate 6D6. Smartchipped e equipada com mira ciberóptica Marconi SUSAT integral.",
    "weapon_sternmeyer_m_95a4_cg_13b_assault_weapon": "Faixa de preço: 695-750eb. Usa pente descartável de 90 tiros e inclui mira óptica 4x.",
    "weapon_stolbovoy_st_5_assault_rifle": "A versão smartchipped custa 1.800eb. Usa munição com cápsula. É comum na União Soviética e no Leste Europeu, mas rara nos EUA e na Grã-Bretanha.",
    "weapon_towa_manufacturing_type_20_advanced_infantry_combat_weapon": "O smartgun eleva a PA para +4; o bipé concede PA +1 em Longa/Extrema. Lança-granadas integral 25x50mm: ArPes, PA 0, dano variável, capacidade 4, CdT 2, C e alcance 150m.",
    "weapon_towa_manufacturing_type_99_assault_rifle": "O smartgun padrão eleva a PA para +3; o bipé concede PA +1 em Longa/Extrema.",
    "weapon_arasaka_wssa_sniper_system": "Smartchipped. Inclui pente helicoidal de 40 flechetes fragmentários sabotados de 3,5mm, silenciador, quebra-chamas e luneta Zeiss 12x com laser, visão noturna e telêmetro.",
    "weapon_barrett_m_90_sniper_rifle": "Usa munição com cápsula e é inútil sem luneta. A versão ciberconectada custa 2.500eb.",
    "weapon_barrett_arasaka_light_20": "Também chamado Type-13 Heavy Sniper Rifle. O penetrador pesado de subcalibre remove 2 PA da blindagem por acerto.",
    "weapon_fr_f6": "Inclui bipé que concede PA +1 em Longa/Extrema, luneta laser assistida por computador e supressor de som.",
    "weapon_nomad_15mm_long_rifle": "Exige COR 9+ para disparar em pé. Inclui montagem com luneta 10x, LowLite, freio de boca, quebra-chamas, gatilho solenoide, bipé e coronha personalizada; desmonta-se em três partes.",
    "weapon_remington_gyro_sniper_rifle": "Cinquenta projéteis custam 400eb. Foguetes têm PA 0 até 75m. Munição API causa 1D6 extra por dois turnos após o impacto; a blindagem não impede esse dano adicional.",
    "weapon_towa_manufacturing_type_00_kai": "Usa munição com cápsula e aprimoramento eletrotérmico. Smartchip e miras computadorizadas acrescentam PA +3.",
    "weapon_heckler_koch_hk77uk": "Opções: estabilizadores Militech 25mm, mira de espectro total para SmartGoggles (+600eb), supressor integral (+200eb), pente estendido (+60eb) e tambor U de 45 tiros (+600eb). Dobrar a coronha melhora o ocultamento de S para J, mas reduz a PA para -1 ao disparar.",
    "weapon_hughes_rocket_rifle": "Usa foguetes de carga moldada. O dano penetrante não é reduzido à metade. Cada projétil custa 20eb.",
    "weapon_m_99_evaw": "Arma EVA de dois canos. O sistema secundário de 25mm tem PA 0, dano 2D6+1 HE, capacidade 10, CdT 1, C, alcance mínimo 10m e efetivo 2.000m. Granadas custam 50eb e foguetes 125eb.",
    "weapon_militech_cyborg_rifle": "Projetado para enfrentar ciborgues e para tiro durante quedas. Aceita munição comum e perfurante; pesa 7,5kg.",
    "weapon_militech_ninja": "Projeto sem cápsula com silenciador integral.",
    "weapon_nomad_357_magnum_automatic_carbine": "PA +1 em tiro único com CdT 2; pode usar rajada de três tiros com CdT 3. Cargas quentes padrão causam 3D6+1. Usa munição com cápsula.",
    "weapon_nomad_357_magnum_lever_action_carbine": "Carabina de alavanca com carregador tubular e munição com cápsula. Cargas quentes padrão causam 3D6+1.",
    "weapon_nomad_44_magnum_lever_action_rifle": "Usa munição com cápsula.",
    "weapon_nomad_7_62mm_bolt_action_rifle": "Usa munição com cápsula.",
    "weapon_nomad_personal_weapon_derivatives": "Modelos atuais usam 10mm sem cápsula para 2D6+3 ou 12mm sem cápsula para 4D6+1; versões antigas usam 5,7mm com cápsula para 3D6. Pode ser tratada como submetralhadora pesada ou fuzil de assalto.",
    "weapon_polymer_one_shot_cannon": "Arma descartável. Metade do dano é real e metade apenas atordoamento; a blindagem não protege e perde 2 PA. Em pane, a arma quebra e há 10% de chance de explodir, causando 2D6 no braço do atirador.",
    "weapon_stein_wasserman_model_f_cyborg_assault_weapon_system": "Usa munição com cápsula e pente rotativo que mistura cargas. HEP: 4D6+2, metade real/metade atordoamento, ignora blindagem e remove 2 PA. API: 4D6+3, divide o PA pela metade e causa 1D6 extra no turno seguinte e 2D6 no posterior, sem proteção da blindagem. Cartuchos ácidos usam os efeitos químicos indicados.",
    "weapon_tsunami_arms_ramjet_rifle": "Dano: 5D6+3 em Curta, 6D6+1 em Média, 7D6 em Longa e 7D6+3 em Extrema. O PA da blindagem é triplicado; o dano penetrante é dobrado.",
    "weapon_constitution_arms_cyclone_squad_support_weapon": "Inclui supressão de recuo, bandoleira e bipé.",
    "weapon_constitution_arms_deluge_crowd_control_weapon": "Arma não letal de controle de multidões. O pente contém 400 dardos soníferos e um cilindro de ar comprimido.",
    "weapon_dover_ga_1112_autogun": "Arma de supressão de área com dois canos e smartgun integral. O kit veicular de 650eb inclui suporte giratório, reservatório de 1.200 tiros e alimentação direta do motor.",
    "weapon_fn_mg_6_one_on_one": "Arma pesada de apoio de pelotão feita para dominar uma única linha de tiro.",
    "weapon_fabrica_de_armes_m_2012hb_saw": "Versão automática especializada da M-2012, com luneta 10x e cano de 31 polegadas.",
    "weapon_heckler_koch_g_6_advanced_squad_automatic": "Versão de apoio de pelotão do sistema G-11, com pente de 100 tiros e óptica integral.",
    "weapon_m2a5hb_browning_50cal_hmg": "Metralhadora pesada Browning modernizada, com munição .50 encapsulada.",
    "weapon_m_60d_medium_machine_gun": "Variante veicular e para atirador de porta da clássica metralhadora média M-60.",
    "weapon_militech_high_power_15": "Arma de apoio de alta velocidade montada em tripé. As cadências indicadas são 20 e 60.",
    "weapon_militech_m_232_squad_assault_automatic_weapon": "Aceita cinta desintegrável de 100 tiros em tambor ou pente padrão de 35 tiros da Mk IV.",
    "weapon_militech_renegade_squad_automatic_weapon": "Aceita cinta desintegrável de 200 tiros ou pentes de 35 tiros das armas Dragon e Mk IV.",
    "weapon_militech_20l_autocannon": "Canhão automático coletivo montado em tripé. Usa munição com cápsula.",
    "weapon_sternmeyer_m_5a_squad_automatic_weapon": "Arma automática de pelotão europeia, construída para apoio sustentado à infantaria.",
    "weapon_towa_manufacturing_type_8_medium_machine_gun": "Também existe mochila de munição com 100 tiros.",
    "weapon_60mm_light_mortar": "Morteiro coletivo com raio de explosão de 5m. Exige dois operadores; com apenas um, a CdT cai para um disparo a cada dois turnos. HE custa 50eb e pesa 1kg; também há fumaça, iluminação e fósforo branco.",
    "weapon_rheinmetall_mauser_mex_cannon": "Canhão semiautomático de ombro com luneta 4x. Um teste de COR 15+ evita 1-2 pontos de contusão no braço ou ombro; falha crítica faz o atirador derrubar a arma.",
    "weapon_commercial_grenade_launcher": "Lança-granadas genérico de tiro único. Pode ser instalado sob um fuzil de assalto ou receber coronha simples para uso independente.",
    "weapon_kenshiri_adachi_f_253_flamethrower": "Lança-chamas dorsal abastecido com napalm liquefeito.",
    "weapon_law": "Arma antitanque leve e descartável, com raio de 2m. O sistema sem recuo e sem contrafluxo permite uso em ambientes fechados.",
    "weapon_hlaw": "Arma antitanque pesada e descartável, com raio de 4m. O sistema sem recuo e sem contrafluxo permite uso em ambientes fechados.",
    "weapon_m_32_automatic_grenade_launcher": "Lança-granadas automático para tripé ou veículo. Usa normalmente granadas de alta velocidade de 40mm; munição 40mm padrão só pode ser disparada em tiro único.",
    "weapon_m_205_grenade_launcher": "Lança-granadas de tiro único e culatra basculante, usado sozinho ou sob o cano.",
    "weapon_m_212_grenade_launcher": "Lança-granadas basculante com tambor de oito tiros; o atirador escolhe qual granada carregada levar à câmara.",
    "weapon_militech_am_3_anti_matter_rifle": "Fuzil de urânio empobrecido com propulsão por foguete. De 0-160m: PA 0 e 1/3 do dano; 160-800m: PA +1 e metade do dano; 800-1.600m: PA 0 e dano total. Exige COR 15+ para evitar 1-3 de contusão sem armação linear ou corpo Beta+. Inclui smartgun ciberóptico e luneta 2-10x LowLite/térmica. Cada munição custa 100eb.",
    "weapon_militech_cowboy_u_55_grenade_launcher": "Lançador semiautomático capaz de rajadas de três tiros. O tambor mistura munições e a mira óptica é integral. Fragmentação, flash, incendiária, concussão, gás e fumaça custam 30eb cada.",
    "weapon_militech_hotshot_l_atgm": "Míssil antitanque guiado por fio, com raio de 4m. Normalmente termográfico, mas aceita guia laser ou óptica. Cada míssil custa 1.500eb.",
    "weapon_militech_mini_grenade_launcher_pump_model": "Lança-minigranadas de ação por bombeamento. Também usa calibre 10. A CdT cai para 1 ao alternar o tipo de munição carregada. Cada minigranada custa 30eb.",
    "weapon_militech_mini_grenade_launcher_drum_model": "Lança-minigranadas de tambor em armação Militech 10. Permite escolher entre munições carregadas e também usa calibre 10. A CdT cai para 1 ao alternar tipos. Cada minigranada custa 30eb.",
    "weapon_militech_rpg_a_grenade_launcher": "Lança-granadas propelido por foguete e disparado do ombro, muito usado nos conflitos da América Central.",
    "weapon_militech_scorpion_16_surface_to_air_missile": "Míssil superfície-ar ativo de busca térmica, com raio de 6m, memória digital de orientação e rastreamento autônomo após travar o alvo.",
    "weapon_militech_urban_missile_launcher": "Lançador de ombro com pente, carregado com MicroMísseis autoguiados, de busca térmica e carga explosiva.",
    "weapon_under_barrel_micromissile_pod": "Pod de tiro único, carregado pela boca e instalado sob uma arma longa. A instalação inicial custa mais 50eb.",
    "weapon_rheinmetall_emg_85_railgun": "CdT de um disparo a cada dois turnos. Efeito Extra-AP reduz a blindagem a 1/4 e o dano penetrante à metade. Exige COR 11 com armação linear ou ACPA. O suporte giroestabilizado evita penalidade de MA, mas tem VE 1; sem ele, exige COR 12 e smartgun, com MA -1 e VE 2. A recarga de energia custa 700eb.",
    "weapon_rostovic_wrist_racate": "Pod cilíndrico de foguetes para o pulso, capaz de tiros únicos ou salvas. Deve ser usado sobre ciberbraço ou luva de combate. Seis foguetes custam 200eb.",
    "weapon_royal_enfield_ordnance_25mm_cockerill_assault_cannon": "Canhão de baixa pressão com projéteis assistidos por foguete. Atirar do quadril impõe PA -1; exige COR 8+, ou o bipé. COR 6+ é necessário para carregar e usar. Munições: AP, HEP e flechete antipessoal APF. HEP causa metade real/metade atordoamento, ignora blindagem e remove 2 PA. APF usa regras de espingarda até 100m.",
    "weapon_towa_manufacturing_type_9_grenade_launcher": "Lança-granadas com tambor de revólver, permitindo escolher entre os tipos carregados.",
    "weapon_tsunami_arms_type_17_anti_armor_rifle": "Fuzil japonês anti-ACPA e antiveículo, com munição encapsulada. O bipé concede PA +1 em Longa/Extrema; miras computadorizadas e smartgun elevam a PA para +3. Cada disparo causa 1 de atordoamento ao atirador. Sem bipé e apoio, exige COR 14, armação linear equivalente ou corpo borgue completo.",
    "weapon_tsunami_arms_type_18_automatic_grenade_launcher": "Lança-granadas automático volumoso, ligado a uma mochila de 25kg. Trocar o pente exige ao menos quatro ações. Mesmo com girobalanço e compensação de recuo, impõe REF -1 e MA -1 pelo peso e volume.",
}
